package pmbusReg

// Access mode
const (
    NA          = 0
    WRITE_BYTE  = 1
    WRITE_WORD  = 2
    READ_BYTE   = 3
    READ_WORD   = 4
    READ_32     = 5
    BLOCK_WRITE = 6
    BLOCK_READ  = 7
    BLOCK_WRP   = 8
    SEND_BYTE   = 9
    RCV_BYTE    = 10
    EXT_CMD     = 11
    MFR_DEF     = 12
)

// Number of bytes
const (
    NB_NA      = 0xFD
    NB_VAR     = 0xFE
    NB_MFR_DEF = 0xFF
)

// Register info structure
type regInfo_t struct {
    write    int
    read     int
    numBytes int
}

var Reg = map[int]regInfo_t{}

const (
    PAGE                      = 0x00
    OPERATION                 = 0x01
    ON_OFF_CONFIG             = 0x02
    CLEAR_FAULTS              = 0x03
    PHASE                     = 0x04
    PAGE_PLUS_WRITE           = 0x05
    PAGE_PLUS_READ            = 0x06
    ZONE_CONFIG               = 0x07
    ZONE_ACTIVE               = 0x08
    RESERVED_09               = 0x09
    RESERVED_0A               = 0x0A
    RESERVED_0B               = 0x0B
    RESERVED_0C               = 0x0C
    RESERVED_0D               = 0x0D
    RESERVED_0E               = 0x0E
    RESERVED_0F               = 0x0F
    WRITE_PROTECT             = 0x10
    STORE_DEFAULT_ALL         = 0x11
    RESTORE_DEFAULT_ALL       = 0x12
    STORE_DEFAULT_CODE        = 0x13
    RESTORE_DEFAULT_CODE      = 0x14
    STORE_USER_ALL            = 0x15
    RESTORE_USER_ALL          = 0x16
    STORE_USER_CODE           = 0x17
    RESTORE_USER_CODE         = 0x18
    CAPABILITY                = 0x19
    QUERY                     = 0x1A
    SMBALERT_MASK             = 0x1B
    RESERVED_1C               = 0x1C
    RESERVED_1D               = 0x1D
    RESERVED_1E               = 0x1E
    RESERVED_1F               = 0x1F
    VOUT_MODE                 = 0x20
    VOUT_COMMAND              = 0x21
    VOUT_TRIM                 = 0x22
    VOUT_CAL_OFFSET           = 0x23
    VOUT_MAX                  = 0x24
    VOUT_MARGIN_HIGH          = 0x25
    VOUT_MARGIN_LOW           = 0x26
    VOUT_TRANSITION_RATE      = 0x27
    VOUT_DROOP                = 0x28
    VOUT_SCALE_LOOP           = 0x29
    VOUT_SCALE_MONITOR        = 0x2A
    VOUT_MIN                  = 0x2B
    RESERVED_2C               = 0x2C
    RESERVED_2D               = 0x2D
    RESERVED_2E               = 0x2E
    RESERVED_2F               = 0x2F
    COEFFICIENTS              = 0x30
    POUT_MAX                  = 0x31
    MAX_DUTY                  = 0x32
    FREQUENCY_SWITCH          = 0x33
    POWER_MODE                = 0x34
    VIN_ON                    = 0x35
    VIN_OFF                   = 0x36
    INTERLEAVE                = 0x37
    IOUT_CAL_GAIN             = 0x38
    IOUT_CAL_OFFSET           = 0x39
    FAN_CONFIG_1_2            = 0x3A
    FAN_COMMAND_1             = 0x3B
    FAN_COMMAND_2             = 0x3C
    FAN_CONFIG_3_4            = 0x3D
    FAN_COMMAND_3             = 0x3E
    FAN_COMMAND_4             = 0x3F
    VOUT_OV_FAULT_LIMIT       = 0x40
    VOUT_OV_FAULT_RESPONSE    = 0x41
    VOUT_OV_WARN_LIMIT        = 0x42
    VOUT_UV_WARN_LIMIT        = 0x43
    VOUT_UV_FAULT_LIMIT       = 0x44
    VOUT_UV_FAULT_RESPONSE    = 0x45
    IOUT_OC_FAULT_LIMIT       = 0x46
    IOUT_OC_FAULT_RESPONSE    = 0x47
    IOUT_OC_LV_FAULT_LIMIT    = 0x48
    IOUT_OC_LV_FAULT_RESPONSE = 0x49
    IOUT_OC_WARN_LIMIT        = 0x4A
    IOUT_UC_FAULT_LIMIT       = 0x4B
    IOUT_UC_FAULT_RESPONSE    = 0x4C
    RESERVED_4D               = 0x4D
    RESERVED_4E               = 0x4E
    OT_FAULT_LIMIT            = 0x4F
    OT_FAULT_RESPONSE         = 0x50
    OT_WARN_LIMIT             = 0x51
    UT_WARN_LIMIT             = 0x52
    UT_FAULT_LIMIT            = 0x53
    UT_FAULT_RESPONSE         = 0x54
    VIN_OV_FAULT_LIMIT        = 0x55
    VIN_OV_FAULT_RESPONSE     = 0x56
    VIN_OV_WARN_LIMIT         = 0x57
    VIN_UV_WARN_LIMIT         = 0x58
    VIN_UV_FAULT_LIMIT        = 0x59
    VIN_UV_FAULT_RESPONSE     = 0x5A
    IIN_OC_FAULT_LIMIT        = 0x5B
    IIN_OC_FAULT_RESPONSE     = 0x5C
    IIN_OC_WARN_LIMIT         = 0x5D
    POWER_GOOD_ON             = 0x5E
    POWER_GOOD_OFF            = 0x5F
    TON_DELAY                 = 0x60
    TON_RISE                  = 0x61
    TON_MAX_FAULT_LIMIT       = 0x62
    TON_MAX_FAULT_RESPONSE    = 0x63
    TOFF_DELAY                = 0x64
    TOFF_FALL                 = 0x65
    TOFF_MAX_WARN_LIMIT       = 0x66
    RESERVED_67               = 0x67
    POUT_OP_FAULT_LIMIT       = 0x68
    POUT_OP_FAULT_RESPONSE    = 0x69
    POUT_OP_WARN_LIMIT        = 0x6A
    PIN_OP_WARN_LIMIT         = 0x6B
    RESERVED_6C               = 0x6C
    RESERVED_6D               = 0x6D
    RESERVED_6E               = 0x6E
    RESERVED_6F               = 0x6F
    RESERVED_70               = 0x70
    RESERVED_71               = 0x71
    RESERVED_72               = 0x72
    RESERVED_73               = 0x73
    RESERVED_74               = 0x74
    RESERVED_75               = 0x75
    RESERVED_76               = 0x76
    RESERVED_77               = 0x77
    STATUS_BYTE               = 0x78
    STATUS_WORD               = 0x79
    STATUS_VOUT               = 0x7A
    STATUS_IOUT               = 0x7B
    STATUS_INPUT              = 0x7C
    STATUS_TEMPERATURE        = 0x7D
    STATUS_CML                = 0x7E
    STATUS_OTHER              = 0x7F
    STATUS_MFR_SPECIFIC       = 0x80
    STATUS_FANS_1_2           = 0x81
    STATUS_FANS_3_4           = 0x82
    READ_KWH_IN               = 0x83
    READ_KWH_OUT              = 0x84
    READ_KWH_CONFIG           = 0x85
    READ_EIN                  = 0x86
    READ_EOUT                 = 0x87
    READ_VIN                  = 0x88
    READ_IIN                  = 0x89
    READ_VCAP                 = 0x8A
    READ_VOUT                 = 0x8B
    READ_IOUT                 = 0x8C
    READ_TEMPERATURE_1        = 0x8D
    READ_TEMPERATURE_2        = 0x8E
    READ_TEMPERATURE_3        = 0x8F
    READ_FAN_SPEED_1          = 0x90
    READ_FAN_SPEED_2          = 0x91
    READ_FAN_SPEED_3          = 0x92
    READ_FAN_SPEED_4          = 0x93
    READ_DUTY_CYCLE           = 0x94
    READ_FREQUENCY            = 0x95
    READ_POUT                 = 0x96
    READ_PIN                  = 0x97
    PMBUS_REVISION            = 0x98
    MFR_ID                    = 0x99
    MFR_MODEL                 = 0x9A
    MFR_REVISION              = 0x9B
    MFR_LOCATION              = 0x9C
    MFR_DATE                  = 0x9D
    MFR_SERIAL                = 0x9E
    APP_PROFILE_SUPPORT       = 0x9F
    MFR_VIN_MIN               = 0xA0
    MFR_VIN_MAX               = 0xA1
    MFR_IIN_MAX               = 0xA2
    MFR_PIN_MAX               = 0xA3
    MFR_VOUT_MIN              = 0xA4
    MFR_VOUT_MAX              = 0xA5
    MFR_IOUT_MAX              = 0xA6
    MFR_POUT_MAX              = 0xA7
    MFR_TAMBIENT_MAX          = 0xA8
    MFR_TAMBIENT_MIN          = 0xA9
    MFR_EFFICIENCY_LL         = 0xAA
    MFR_EFFICIENCY_HL         = 0xAB
    MFR_PIN_ACCURACY          = 0xAC
    IC_DEVICE_ID              = 0xAD
    IC_DEVICE_REV             = 0xAE
    RESERVED_AF               = 0xAF
    USER_DATA_00              = 0xB0
    USER_DATA_01              = 0xB1
    USER_DATA_02              = 0xB2
    USER_DATA_03              = 0xB3
    USER_DATA_04              = 0xB4
    USER_DATA_05              = 0xB5
    USER_DATA_06              = 0xB6
    USER_DATA_07              = 0xB7
    USER_DATA_08              = 0xB8
    USER_DATA_09              = 0xB9
    USER_DATA_10              = 0xBA
    USER_DATA_11              = 0xBB
    USER_DATA_12              = 0xBC
    USER_DATA_13              = 0xBD
    USER_DATA_14              = 0xBE
    USER_DATA_15              = 0xBF
    MFR_MAX_TEMP_1            = 0xC0
    MFR_MAX_TEMP_2            = 0xC1
    MFR_MAX_TEMP_3            = 0xC2
    RESERVED_C3               = 0xC3
    MFR_SPECIFIC_C4           = 0xC4
    MFR_SPECIFIC_C5           = 0xC5
    MFR_SPECIFIC_C6           = 0xC6
    MFR_SPECIFIC_C7           = 0xC7
    MFR_SPECIFIC_C8           = 0xC8
    MFR_SPECIFIC_C9           = 0xC9
    MFR_SPECIFIC_CA           = 0xCA
    MFR_SPECIFIC_CB           = 0xCB
    MFR_SPECIFIC_CC           = 0xCC
    MFR_SPECIFIC_CD           = 0xCD
    MFR_SPECIFIC_CE           = 0xCE
    MFR_SPECIFIC_CF           = 0xCF
    MFR_SPECIFIC_D0           = 0xD0
    MFR_SPECIFIC_D1           = 0xD1
    MFR_SPECIFIC_D2           = 0xD2
    MFR_SPECIFIC_D3           = 0xD3
    MFR_SPECIFIC_D4           = 0xD4
    MFR_SPECIFIC_D5           = 0xD5
    MFR_SPECIFIC_D6           = 0xD6
    MFR_SPECIFIC_D7           = 0xD7
    MFR_SPECIFIC_D8           = 0xD8
    MFR_SPECIFIC_D9           = 0xD9
    MFR_SPECIFIC_DA           = 0xDA
    MFR_SPECIFIC_DB           = 0xDB
    MFR_SPECIFIC_DC           = 0xDC
    MFR_SPECIFIC_DD           = 0xDD
    MFR_SPECIFIC_DE           = 0xDE
    MFR_SPECIFIC_DF           = 0xDF
    MFR_SPECIFIC_E0           = 0xE0
    MFR_SPECIFIC_E1           = 0xE1
    MFR_SPECIFIC_E2           = 0xE2
    MFR_SPECIFIC_E3           = 0xE3
    MFR_SPECIFIC_E4           = 0xE4
    MFR_SPECIFIC_E5           = 0xE5
    MFR_SPECIFIC_E6           = 0xE6
    MFR_SPECIFIC_E7           = 0xE7
    MFR_SPECIFIC_E8           = 0xE8
    MFR_SPECIFIC_E9           = 0xE9
    MFR_SPECIFIC_EA           = 0xEA
    MFR_SPECIFIC_EB           = 0xEB
    MFR_SPECIFIC_EC           = 0xEC
    MFR_SPECIFIC_ED           = 0xED
    MFR_SPECIFIC_EE           = 0xEE
    MFR_SPECIFIC_EF           = 0xEF
    MFR_SPECIFIC_F0           = 0xF0
    MFR_SPECIFIC_F1           = 0xF1
    MFR_SPECIFIC_F2           = 0xF2
    MFR_SPECIFIC_F3           = 0xF3
    MFR_SPECIFIC_F4           = 0xF4
    MFR_SPECIFIC_F5           = 0xF5
    MFR_SPECIFIC_F6           = 0xF6
    MFR_SPECIFIC_F7           = 0xF7
    MFR_SPECIFIC_F8           = 0xF8
    MFR_SPECIFIC_F9           = 0xF9
    MFR_SPECIFIC_FA           = 0xFA
    MFR_SPECIFIC_FB           = 0xFB
    MFR_SPECIFIC_FC           = 0xFC
    MFR_SPECIFIC_FD           = 0xFD
    MFR_SPECIFIC_COMMAND_EXT  = 0xFE
    PMBUS_COMMAND_EXT         = 0xFF
)

func init() {
    Reg[PAGE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[OPERATION] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[ON_OFF_CONFIG] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[CLEAR_FAULTS] = regInfo_t{SEND_BYTE, NA, 0}
    Reg[PHASE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[PAGE_PLUS_WRITE] = regInfo_t{BLOCK_WRITE, NA, NB_VAR}
    Reg[PAGE_PLUS_READ] = regInfo_t{NA, BLOCK_WRP, NB_VAR}
    Reg[ZONE_CONFIG] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[ZONE_ACTIVE] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[RESERVED_09] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0A] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0B] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0C] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0D] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0E] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_0F] = regInfo_t{NA, NA, NB_NA}
    Reg[WRITE_PROTECT] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STORE_DEFAULT_ALL] = regInfo_t{SEND_BYTE, NA, 0}
    Reg[RESTORE_DEFAULT_ALL] = regInfo_t{SEND_BYTE, NA, 0}
    Reg[STORE_DEFAULT_CODE] = regInfo_t{WRITE_BYTE, NA, 1}
    Reg[RESTORE_DEFAULT_CODE] = regInfo_t{WRITE_BYTE, NA, 1}
    Reg[STORE_USER_ALL] = regInfo_t{SEND_BYTE, NA, 0}
    Reg[RESTORE_USER_ALL] = regInfo_t{SEND_BYTE, NA, 0}
    Reg[STORE_USER_CODE] = regInfo_t{WRITE_BYTE, NA, 1}
    Reg[RESTORE_USER_CODE] = regInfo_t{WRITE_BYTE, NA, 1}
    Reg[CAPABILITY] = regInfo_t{NA, READ_BYTE, 1}
    Reg[QUERY] = regInfo_t{NA, BLOCK_WRP, 1}
    Reg[SMBALERT_MASK] = regInfo_t{WRITE_WORD, BLOCK_WRP, 2}
    Reg[RESERVED_1C] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_1D] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_1E] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_1F] = regInfo_t{NA, NA, NB_NA}
    Reg[VOUT_MODE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[VOUT_COMMAND] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_TRIM] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_CAL_OFFSET] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_MAX] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_MARGIN_HIGH] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_MARGIN_LOW] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_TRANSITION_RATE] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_DROOP] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_SCALE_LOOP] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_SCALE_MONITOR] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_MIN] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[RESERVED_2C] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_2D] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_2E] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_2F] = regInfo_t{NA, NA, NB_NA}
    Reg[COEFFICIENTS] = regInfo_t{NA, BLOCK_WRP, 5}
    Reg[POUT_MAX] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[MAX_DUTY] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[FREQUENCY_SWITCH] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[POWER_MODE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[VIN_ON] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VIN_OFF] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[INTERLEAVE] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_CAL_GAIN] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_CAL_OFFSET] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[FAN_CONFIG_1_2] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[FAN_COMMAND_1] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[FAN_COMMAND_2] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[FAN_CONFIG_3_4] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[FAN_COMMAND_3] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[FAN_COMMAND_4] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_OV_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_OV_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[VOUT_OV_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_UV_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_UV_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VOUT_UV_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[IOUT_OC_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_OC_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[IOUT_OC_LV_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_OC_LV_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[IOUT_OC_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_UC_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IOUT_UC_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[RESERVED_4D] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_4E] = regInfo_t{NA, NA, NB_NA}
    Reg[OT_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[OT_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[OT_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[UT_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[UT_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[UT_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[VIN_OV_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VIN_OV_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[VIN_OV_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VIN_UV_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VIN_UV_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[VIN_UV_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[IIN_OC_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[IIN_OC_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[IIN_OC_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[POWER_GOOD_ON] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[POWER_GOOD_OFF] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TON_DELAY] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TON_RISE] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TON_MAX_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TON_MAX_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[TOFF_DELAY] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TOFF_FALL] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[TOFF_MAX_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[RESERVED_67] = regInfo_t{NA, NA, NB_NA}
    Reg[POUT_OP_FAULT_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[POUT_OP_FAULT_RESPONSE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[POUT_OP_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[PIN_OP_WARN_LIMIT] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[RESERVED_6C] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_6D] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_6E] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_6F] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_70] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_71] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_72] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_73] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_74] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_75] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_76] = regInfo_t{NA, NA, NB_NA}
    Reg[RESERVED_77] = regInfo_t{NA, NA, NB_NA}
    Reg[STATUS_BYTE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_WORD] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[STATUS_VOUT] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_IOUT] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_INPUT] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_TEMPERATURE] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_CML] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_OTHER] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_MFR_SPECIFIC] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_FANS_1_2] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[STATUS_FANS_3_4] = regInfo_t{WRITE_BYTE, READ_BYTE, 1}
    Reg[READ_KWH_IN] = regInfo_t{NA, READ_32, 4}
    Reg[READ_KWH_OUT] = regInfo_t{NA, READ_32, 4}
    Reg[READ_KWH_CONFIG] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[READ_EIN] = regInfo_t{NA, BLOCK_READ, 5}
    Reg[READ_EOUT] = regInfo_t{NA, BLOCK_READ, 5}
    Reg[READ_VIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_IIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_VCAP] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_VOUT] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_IOUT] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_TEMPERATURE_1] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_TEMPERATURE_2] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_TEMPERATURE_3] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_FAN_SPEED_1] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_FAN_SPEED_2] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_FAN_SPEED_3] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_FAN_SPEED_4] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_DUTY_CYCLE] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_FREQUENCY] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_POUT] = regInfo_t{NA, READ_WORD, 2}
    Reg[READ_PIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[PMBUS_REVISION] = regInfo_t{NA, READ_BYTE, 1}
    Reg[MFR_ID] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_MODEL] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_REVISION] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_LOCATION] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_DATE] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_SERIAL] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[APP_PROFILE_SUPPORT] = regInfo_t{NA, BLOCK_READ, NB_VAR}
    Reg[MFR_VIN_MIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_VIN_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_IIN_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_PIN_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_VOUT_MIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_VOUT_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_IOUT_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_POUT_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_TAMBIENT_MAX] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_TAMBIENT_MIN] = regInfo_t{NA, READ_WORD, 2}
    Reg[MFR_EFFICIENCY_LL] = regInfo_t{NA, BLOCK_READ, 1}
    Reg[MFR_EFFICIENCY_HL] = regInfo_t{NA, BLOCK_READ, 1}
    Reg[MFR_PIN_ACCURACY] = regInfo_t{NA, READ_BYTE, 1}
    Reg[IC_DEVICE_ID] = regInfo_t{NA, BLOCK_READ, NB_VAR}
    Reg[IC_DEVICE_REV] = regInfo_t{NA, BLOCK_READ, NB_VAR}
    Reg[RESERVED_AF] = regInfo_t{NA, NA, NB_NA}
    Reg[USER_DATA_00] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_01] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_02] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_03] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_04] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_05] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_06] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_07] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_08] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_09] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_10] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_11] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_12] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_13] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_14] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[USER_DATA_15] = regInfo_t{BLOCK_WRITE, BLOCK_READ, NB_VAR}
    Reg[MFR_MAX_TEMP_1] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[MFR_MAX_TEMP_2] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[MFR_MAX_TEMP_3] = regInfo_t{WRITE_WORD, READ_WORD, 2}
    Reg[RESERVED_C3] = regInfo_t{NA, NA, NB_NA}
    Reg[MFR_SPECIFIC_C4] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_C5] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_C6] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_C7] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_C8] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_C9] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CA] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CB] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CC] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CD] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CE] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_CF] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D0] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D1] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D2] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D3] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D4] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D5] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D6] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D7] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D8] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_D9] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DA] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DB] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DC] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DD] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DE] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_DF] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E0] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E1] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E2] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E3] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E4] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E5] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E6] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E7] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E8] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_E9] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_EA] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_EB] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_EC] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_ED] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_EE] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_EF] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F0] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F1] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F2] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F3] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F4] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F5] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F6] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F7] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F8] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_F9] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_FA] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_FB] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_FC] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_FD] = regInfo_t{MFR_DEF, MFR_DEF, NB_MFR_DEF}
    Reg[MFR_SPECIFIC_COMMAND_EXT] = regInfo_t{EXT_CMD, EXT_CMD, NB_MFR_DEF}
    Reg[PMBUS_COMMAND_EXT] = regInfo_t{EXT_CMD, EXT_CMD, NB_MFR_DEF}
}
