---
PLATFORM_CONFIG:
    HOST: HOST
    NIC: BIODONA_D4 BIODONA_D5 FORIO NAPLES100 NAPLES100DELL NAPLES100IBM NAPLES100HPE NAPLES25 NAPLES25OCP NAPLES25SWM VOMERO VOMERO2 NAPLES25SWMDELL NAPLES25SWM833 ORTANO ORTANO2 ORTANO2A ORTANO2AC ORTANO2I ORTANO2S LACONADELL LACONA POMONTEDELL POMONTE LACONA32DELL LACONA32 GINESTRA_D4 GINESTRA_D5 LENI LENI48G
    TOR: TAORMINA
