---
version: 2.0
builds:
  build-amd64-giglio:
    commands: [ "sh", "-c", "cd build; make amd64 asic=giglio asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_giglio.tar
  build-arm64-giglio:
    commands: [ "sh", "-c", "cd build; make arm64 asic=giglio asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_giglio.tar
    - /psdiag/build/images/nic_util.tar # save nic_util only once instead of for every asic
  build-amd64-elba:
    commands: [ "sh", "-c", "cd build; make amd64 asic=elba asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_elba.tar
  build-arm64-elba:
    commands: [ "sh", "-c", "cd build; make arm64 asic=elba asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_elba.tar
  build-amd64-capri:
    commands: [ "sh", "-c", "cd build; make amd64 asic=capri asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_capri.tar
  build-arm64-capri:
    commands: [ "sh", "-c", "cd build; make arm64 asic=capri asiclib=stable" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_capri.tar

  build-amd64-giglio-tot:
    commands: [ "sh", "-c", "cd build; make amd64 asic=giglio asiclib=latest" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_giglio.tar
  build-arm64-giglio-tot:
    commands: [ "sh", "-c", "cd build; make arm64 asic=giglio asiclib=latest" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_giglio.tar
  build-amd64-elba-tot:
    commands: [ "sh", "-c", "cd build; make amd64 asic=elba asiclib=latest" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_elba.tar
  build-arm64-elba-tot:
    commands: [ "sh", "-c", "cd build; make arm64 asic=elba asiclib=latest" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_elba.tar

  package-giglio-mfg-script:
    commands: [ "sh", "-c", "asic_type=giglio bash -ex qa-infra/package-mfg-script.sh" ]
    owners: ["email:nabeel@pensando.io"]
    artifacts:
    - /psdiag/jobd/jobd.tar.gz
  package-elba-mfg-script:
    commands: [ "sh", "-c", "asic_type=elba bash -ex qa-infra/package-mfg-script.sh" ]
    owners: ["email:nabeel@pensando.io"]
    artifacts:
    - /psdiag/jobd/jobd.tar.gz
  package-capri-mfg-script:
    commands: [ "sh", "-c", "asic_type=capri bash -ex qa-infra/package-mfg-script.sh" ]
    owners: ["email:nabeel@pensando.io"]
    artifacts:
    - /psdiag/jobd/jobd.tar.gz
  package-fw-assets:
    commands: [ "sh", "-c", "bash -ex qa-infra/package-fw.sh" ]
    owners: ["email:nabeel@pensando.io"]
    artifacts:
    - /psdiag/fw.tar

queue_name: asic
image:
  bind_dir: "/psdiag"
host_mounts:
  "/hw": "/vol/hw"

jobs:
  asset-build:
    labels: ["CI-DIAG-Build", "CI-DIAG-Release"]
  qa-infra/daily:
    labels: ["CI-DIAG-Daily"]
  test/ScanDL:
    labels: ["CI-DIAG-ScanDL"]
  test/DL:
    labels: ["CI-DIAG-DL"]
  test/P2C:
    labels: ["CI-DIAG-P2C"]
  test/4C:
    labels: ["CI-DIAG-4C", "CI-DIAG-Regression"]
  #test/RDT:
  #  labels: ["CI-DIAG-RDT"]
  test/ORT:
    labels: ["CI-DIAG-ORT"]
  #test/SRN:
  #  labels: ["CI-DIAG-SRN"]
  test/SWI:
    labels: ["CI-DIAG-SWI"]
  test/FST:
    labels: ["CI-DIAG-FST"]
### NIC_TYPE TEST BUNDLE ###
  test/ginestra:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ginestra"]
  test/monterey:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-monterey"]
  test/ortano-adicr-s4:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adicr-s4"]
  test/ortano-solo-s4:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-solo-s4"]
  test/ortano-adi-ibm:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adi-ibm"]
  test/ortano-adicr-msft:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adicr-msft"]
  test/ortano-solo-msft:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-solo-msft"]
  test/ortano-adi-msft:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adi-msft"]
  test/ortano-adicr-orc:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adicr-orc"]
  test/ortano-solo-orc:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-solo-orc"]
  test/ortano-interp-orc:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-interp-orc"]
  test/ortano-adi-orc:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-adi-orc"]
  test/ortano-ti-orc:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-ortano-ti-orc"]
  test/naples25swm-dell:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-naples25swm-dell"]
  test/naples25swm-hpe:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-naples25swm-hpe"]
  test/naples100:
    labels: ["CI-DIAG-Model", "CI-DIAG-Build", "CI-DIAG-naples100"]
### END NIC_TYPE TEST BUNDLE ###
### NIC_TYPE ASIC TEST BUNDLE ###
  test-asic/ginestra:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ginestra"]
  test-asic/monterey:
    labels: ["CI-ASIC-TOT", "CI-ASIC-monterey"]
  test-asic/ortano-adicr-s4:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adicr-s4"]
  test-asic/ortano-solo-s4:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-solo-s4"]
  test-asic/ortano-adi-ibm:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adi-ibm"]
  test-asic/ortano-adicr-msft:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adicr-msft"]
  test-asic/ortano-solo-msft:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-solo-msft"]
  test-asic/ortano-adi-msft:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adi-msft"]
  test-asic/ortano-adicr-orc:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adicr-orc"]
  test-asic/ortano-solo-orc:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-solo-orc"]
  test-asic/ortano-interp-orc:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-interp-orc"]
  test-asic/ortano-adi-orc:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-adi-orc"]
  test-asic/ortano-ti-orc:
    labels: ["CI-ASIC-TOT", "CI-ASIC-ortano-ti-orc"]
### END NIC_TYPE ASIC TEST BUNDLE ###

dependencies:
  .:
    - reference: test/FST
  test/infra:
    - reference: test/FST
  qa/infra:
    - reference: test/FST
  build:
    - reference: asset-build
  asset-build:
    - reference: asset-build

  diag:
    - reference: test/P2C
      exclude_dirs: ["mfg"]

  diag/mfg:
### NIC_TYPE DEPENDENCY ###
    - reference: test/ginestra
      exclude_dirs: ["scripts"]
    - reference: test/monterey
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adicr-s4
      exclude_dirs: ["scripts"]
    - reference: test/ortano-solo-s4
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adi-ibm
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adicr-msft
      exclude_dirs: ["scripts"]
    - reference: test/ortano-solo-msft
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adi-msft
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adicr-orc
      exclude_dirs: ["scripts"]
    - reference: test/ortano-solo-orc
      exclude_dirs: ["scripts"]
    - reference: test/ortano-interp-orc
      exclude_dirs: ["scripts"]
    - reference: test/ortano-adi-orc
      exclude_dirs: ["scripts"]
    - reference: test/ortano-ti-orc
      exclude_dirs: ["scripts"]
    - reference: test/naples25swm-dell
      exclude_dirs: ["scripts"]
    - reference: test/naples25swm-hpe
      exclude_dirs: ["scripts"]
    - reference: test/naples100
      exclude_dirs: ["scripts"]
### END NIC_TYPE DEPENDENCY ###
  diag/mfg/scripts:
    - reference: test/FST
