---
version: 2.0
builds:
  build-amd64-elba:
    commands: [ "sh", "-c", "cd build; make amd64 asic=elba asiclib=unpackaged" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_elba.tar
  build-arm64-elba:
    commands: [ "sh", "-c", "cd build; make arm64 asic=elba asiclib=unpackaged" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_elba.tar
    owners: ["email:xin@pensando.io"]
  build-amd64-capri:
    commands: [ "sh", "-c", "cd build; make amd64 asic=capri asiclib=unpackaged" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_amd64_capri.tar
  build-arm64-capri:
    commands: [ "sh", "-c", "cd build; make arm64 asic=capri asiclib=unpackaged" ]
    owners: ["email:xin@pensando.io"]
    artifacts:
    - /psdiag/build/images/image_arm64_capri.tar
    owners: ["email:xin@pensando.io"]

queue_name: asic
image:
  bind_dir: "/psdiag"
host_mounts:
  "/hw": "/vol/hw"

jobs:
  asset-build:
    labels: ["CI-DIAG-Build"]
  test/sanity/capri:
    labels: ["CI-DIAG-Build"]
  test/sanity/elba:
    labels: ["CI-DIAG-Build"]
      #  test/precheckin/capri:
      #test/precheckin/elba:
      #test/regression/capri:
      #test/regression/elba:
