/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ../../common/i2c/i2c.i

package i2c

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_i2c_3b2501dbc6abdc62(uintptr_t arg1);
extern uintptr_t _wrap_new_I2c_i2c_3b2501dbc6abdc62(swig_intgo arg1);
extern swig_intgo _wrap_I2c_Read_i2c_3b2501dbc6abdc62(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_voidp arg4, swig_intgo arg5);
extern void _wrap_delete_I2c_i2c_3b2501dbc6abdc62(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_i2c_3b2501dbc6abdc62(C.uintptr_t(_swig_i_0))
}

type SwigcptrI2c uintptr

func (p SwigcptrI2c) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrI2c) SwigIsI2c() {
}

func NewI2c(arg1 int) (_swig_ret I2c) {
	var swig_r I2c
	_swig_i_0 := arg1
	swig_r = (I2c)(SwigcptrI2c(C._wrap_new_I2c_i2c_3b2501dbc6abdc62(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrI2c) Read(arg2 int, arg3 int, arg4 *uint, arg5 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_I2c_Read_i2c_3b2501dbc6abdc62(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func DeleteI2c(arg1 I2c) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_I2c_i2c_3b2501dbc6abdc62(C.uintptr_t(_swig_i_0))
}

type I2c interface {
	Swigcptr() uintptr
	SwigIsI2c()
	Read(arg2 int, arg3 int, arg4 *uint, arg5 int) (_swig_ret int)
}


