#!/usr/bin/env python

import argparse
import logging
import os
import redis
import shlex
import sys
from time import sleep

from IPython import embed
from traitlets.config.loader import Config
from IPython.terminal.prompts import Prompts, Token
from IPython.terminal.embed import InteractiveShellEmbed

from diagEngineHost import diagEngineHost, diagSts

#==========================================================
parser = argparse.ArgumentParser(description="Diagnostic inteface")
parser.add_argument("-v", "--verbose", action="store_true")
group = parser.add_mutually_exclusive_group()
group.add_argument("-sh", "--shell", action="store_true", help="Get into diag shell")
group.add_argument("-r", "--runtest", action="store_true", help="Run test; format: diag -r -c CARD_IDX [-d DSP] [-t TEST] [-p PARAM_LIST]")
group.add_argument("-skip", "--skiptest", action="store_true", help="Skip test; format: diag -skip -c CARD_IDX [-d DSP][-t TEST]")
group.add_argument("-uskip", "--unskiptest", action="store_true", help="Unskip test; format: diag -skip -c CARD_IDX [-d DSP][-t TEST]")

group.add_argument("-pr", "--parallelRuntest", action='append', type=str, help="")

group.add_argument("-scard", "--showCard", action="store_true", help="Show card list")
group.add_argument("-sdsp", "--showDsp", action="store_true", help="Show DSP list; if cardName specified, show DSP list on particular card; Otherwise, show DSPs of all cards")
group.add_argument("-stest", "--showTest", action="store_true", help="Show test list; if cardName and dspName specified, show test list on particular card; Otherwise, show tests of all cards")
group.add_argument("-shist", "--showHist", action="store_true", help="display per test pass/fail/timeout history; format: diag -shist [-c CARD_IDX] [-d DSP]")
group.add_argument("-sskip", "--showSkip", action="store_true", help="Show skeped test list")

group.add_argument("-csys", "--cleanSystem", action="store_true", help="Housekeeping command, clean all the queues and queue status")
group.add_argument("-chist", "--cleanHistory", action="store_true", help="Housekeeping command, clean test histories")

group.add_argument("-soe", "--stopOnErr", type=int, help="Stop on error; 0: disable; 1: enable", default=100)

parser.add_argument("-c", "--cardidx", help="Target card index, e.g. NIC1", type=str, default='')
parser.add_argument("-d", "--dspname", help="Target DSP name, e.g. PMBUS", type=str, default='')
parser.add_argument("-t", "--testname", help="Target test name, e.g. INTR", type=str, default='')
parser.add_argument("-p", "--parameter", help="Test Parameter, e.g. \"timeout=10 mask=0x1F\"", type=str, default='')


args = parser.parse_args()

# if no arguement specified
if (len(sys.argv) == 1):
    parser.print_help()
    sys.exit()

#==========================================================
diaghost = diagEngineHost()
diagsts = diagSts()

#==========================================================
# Start inter active mode
if args.shell == True:
    dshid = diaghost.dshid
    promptStr = 'DiagSH[{}]'
    prompt = promptStr.format(dshid)
    
    class MyPrompt(Prompts):
        def in_prompt_tokens(self, cli=None):
            return [(Token.Prompt, prompt)]
        def out_prompt_tokens(self, cli=None):
            return [(Token.Prompt, prompt)]
    
    try:
        get_ipython
    except NameError:
        banner  ='Entering Diag Shell'
        exit_msg = 'Exiting Diag Shell'
        cfg = Config()
        prompt_config = cfg.TerminalInteractiveShell.prompts_class
        prompt_config.in_template = 'DiagSH: '
    
    else:
        banner = '*** Nested DiagSHELL ***'
        exit_msg = '*** Back in main DiagSHELL ***'
    
    ipshell = InteractiveShellEmbed(banner1=banner, exit_msg=exit_msg)
    
    ipshell.prompts = MyPrompt(ipshell)
    
    ipshell()
    sys.exit()

# Convert input parameter string to 
def convertParam(param):
    paramList = dict()
    paramList1 = param.split()
    for item in paramList1:
        paramkv = item.split('=')
        paramList[paramkv[0]] = paramkv[1]
    return paramList

if args.runtest == True:
    paramList = convertParam(args.parameter)
    diaghost.runTest(args.cardidx, args.dspname, args.testname, paramList)
    sys.exit()

if args.stopOnErr == 0 or args.stopOnErr == 1:
    diaghost.setStopOnErr(args.stopOnErr)
    sys.exit()

if args.skiptest == True:
    diaghost.skip(args.cardidx, args.dspname, args.testname)
    sys.exit()

if args.unskiptest == True:
    diaghost.unskip(args.cardidx, args.dspname, args.testname)
    sys.exit()

if args.showSkip == True:
    diagsts.showSkip()
    sys.exit()

if args.showCard == True:
    diagsts.showCard()
    sys.exit()

if args.showDsp == True:
    diagsts.showDsp(args.cardidx)
    sys.exit()

if args.showTest == True:
    diagsts.showTest(args.cardidx, args.dspname)
    sys.exit()

if args.showHist == True:
    diagsts.showHist(args.cardidx, args.dspname)
    sys.exit()

if args.cleanSystem == True:
    diagsts.cleanSys()
    sys.exit()

if args.cleanHistory == True:
    diagsts.cleanHist()
    sys.exit()

if args.parallelRuntest != None:
    paraTest = args.parallelRuntest
    testItems = []
    for test in paraTest:
        test = test.split()[1:]

        # In parallel run, parameter is encapsulated by quote signs.
        # Following code is to remove the quote signs and concatenate all parameter into
        # one single parameter string
        test1 = []
        paramStart = 0
        paramEnd = 0
        item1 = ""
        for item in test:
            # parameter concanetation starts
            if item[0] == "\"":
                item = item[1:]
                paramStart = 1
            # parameter concanetation ends
            if item[len(item)-1] == "\"":
                item = item[:len(item)-1]
                paramEnd = 1

            if paramStart == 1:
                item1 = item1 + " " + item
            else:
                item1 = item
                test1.append(item1)
                item1 = ""

            if paramEnd == 1:
                paramStart = 0
                paramEnd = 0
                test1.append(item1)
                item1 = ""

        argss = parser.parse_args(test1)
        param = argss.parameter
        if param[0] == "\"":
            param = param[1:]
        if param[len(param)-1] == "\"":
            param = param[0:len(param)-1]
        paramList = convertParam(param)
        testItems.append([argss.cardidx, argss.dspname, argss.testname, paramList])
    diaghost.paraRun(testItems)
