---
version: 2.0

queue_name: asic
image:
  bind_dir: "/psdiag"
  work_dir: "/psdiag"

host_mounts:
  "/hw": "/vol/hw"

logfiles:
 - /psdiag/diag_detailed_log.tgz

e2e-targets:
  ortano-ti-orc:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-ti-orc --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-ti
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adi-orc:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adi-orc --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adi
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-interp-orc:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-interp-orc --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-interp
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-solo-orc:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-solo-orc --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-solo
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adicr-orc:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adicr-orc --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adicr
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adi-msft:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adi-msft --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adi
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-solo-msft:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-solo-msft --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-solo
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adicr-msft:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adicr-msft --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adicr
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adi-ibm:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adi-ibm --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adi
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-solo-s4:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-solo-s4 --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-solo
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ortano-adicr-s4:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ortano-adicr-s4 --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ortano-adicr
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  lacona-hpe:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type lacona-hpe --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: laconahpe
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  lacona-dell:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type lacona-dell --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: laconadell
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  pomonte-dell:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type pomonte-dell --testbed /warmd.json --test-type precheckin --asic elba --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-elba-tot
     - build-arm64-elba-tot
     - package-elba-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: pomonte
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  ginestra:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type ginestra --testbed /warmd.json --test-type precheckin --asic giglio --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-giglio-tot
     - build-arm64-giglio-tot
     - package-giglio-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: elba
         - name: ginestra
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  pollara:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type pollara --testbed /warmd.json --test-type precheckin --asic salina --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-salina-tot
     - build-arm64-salina-tot
     - package-salina-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: matera
         - name: pollara
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

  leni48:
    commands: ["sh", "-c", "/psdiag/test/run_mfg_job.sh --nic-type leni48 --testbed /warmd.json --test-type precheckin --asic salina --testsuite /psdiag/test/spec/testsuites/SWI.testsuite"]
    owners: ["email:nabeel@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-amd64-salina-tot
     - build-arm64-salina-tot
     - package-salina-mfg-script
     - package-fw-assets
    deployment:
      skip-pxe-install: true
    resources:
     - generic:
       - type: MTP
         vendor: Pensando
         count: 1
         props:
         - name: mtp-nic-processor
           value: matera
         - name: leni48
           value: yes
    provision:
      username: diag
      password: lab123
      vars:
        BmOs: linux

