UUT-9001:
    MODE: ""
    TS: "10.9.6.24"
    TS_PORT: "30"
    TS_USERID: ""
    TS_PASSWORD: "N0isystem$"
    USB_TS: ""
    USB_TS_PORT: ""
    USB_TS_USERID: ""
    USB_TS_PASSWORD: ""
    APC1: "10.9.6.13"
    APC1_PORT: "1"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: ""
    APC2_PASSWORD: ""
    IP: ""
    USERID: "admin"
    PASSWORD: "YourPaSsWoRd"
    ALIAS: "L013"
