---
NAPLES100:

    P2C:
        INIT:
            SYSMON: util/sysmon:-c
            LINK_TEST: util/periutil
            
        UUT_SEQ:
            INIT:
            PARAM: TEMPSENSOR:DEV_ID:ite:2 
                   TEMPSENSOR:TEMP:ite:3
            SKIP: RTC 
            TEST: ALL
            CLEANUP:
        
        UUT_PARA:
            INIT:
            SKIP:
            TEST: PMBUS RTC:I2C
            CLEANUP:

...
