---
version: 2.0
queue_name: asic

targets:
  daily-diag-images:
    commands: [ "sh", "-c", "/psdiag/qa-infra/daily/daily-diag.sh" ]
    owners: ["email:xin@pensando.io"]
    build-dependencies:
    - build-amd64-capri
    - build-arm64-capri
    - build-amd64-elba
    - build-arm64-elba
    - build-amd64-giglio
    - build-arm64-giglio
    - build-amd64-salina
    - build-arm64-salina
    - build-amd64-vulcano

image:
  bind_dir: "/psdiag"
  work_dir: "/psdiag"

host_mounts:
  "/hw": "/vol/hw"

