---
version: 2.0
queue_name: asic

targets:
  push_diag_toolset:
    commands: [ "sh", "-c", "cd /psdiag/asset-build; ./push_build.sh"]
    owners: ["email:nabeel@pensando.io"]
    build-dependencies:
    - build-amd64-elba
    - build-arm64-elba
    - build-amd64-capri
    - build-arm64-capri
image:
  bind_dir: "/psdiag"
  work_dir: "/psdiag/asset-build"
