# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import certificates_pb2 as certificates__pb2


class CertificatesStub(object):
  """Service to issue manufacturing certificates for NAPLES cards
  A manufacturing certificate contains card identifiers and the public endorsement key (EK)
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IssueEKCertificate = channel.unary_unary(
        '/api.Certificates/IssueEKCertificate',
        request_serializer=certificates__pb2.EKCertificateRequest.SerializeToString,
        response_deserializer=certificates__pb2.Certificate.FromString,
        )


class CertificatesServicer(object):
  """Service to issue manufacturing certificates for NAPLES cards
  A manufacturing certificate contains card identifiers and the public endorsement key (EK)
  """

  def IssueEKCertificate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CertificatesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IssueEKCertificate': grpc.unary_unary_rpc_method_handler(
          servicer.IssueEKCertificate,
          request_deserializer=certificates__pb2.EKCertificateRequest.FromString,
          response_serializer=certificates__pb2.Certificate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.Certificates', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
