# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import keys_pb2 as keys__pb2


class KeysStub(object):
  """SERVICE TO FETCH MANUFACTURING KEYS FOR NAPLES CARDS
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FetchKeySet = channel.unary_unary(
        '/keys.Keys/FetchKeySet',
        request_serializer=keys__pb2.FetchKeySetRequest.SerializeToString,
        response_deserializer=keys__pb2.KeySet.FromString,
        )


class KeysServicer(object):
  """SERVICE TO FETCH MANUFACTURING KEYS FOR NAPLES CARDS
  """

  def FetchKeySet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeysServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FetchKeySet': grpc.unary_unary_rpc_method_handler(
          servicer.FetchKeySet,
          request_deserializer=keys__pb2.FetchKeySetRequest.FromString,
          response_serializer=keys__pb2.KeySet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'keys.Keys', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
