# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keys.proto',
  package='keys',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nkeys.proto\x12\x04keys\" \n\x12\x46\x65tchKeySetRequest\x12\n\n\x02ID\x18\x01 \x01(\t\"\x9a\x02\n\x06KeySet\x12\"\n\x1a\x43hipManufacturerPublicKey0\x18\x01 \x01(\x0c\x12$\n\x1cSystemManufacturerPublicKey0\x18\x02 \x01(\x0c\x12\"\n\x1a\x43hipManufacturerPublicKey1\x18\x03 \x01(\x0c\x12$\n\x1cSystemManufacturerPublicKey1\x18\x04 \x01(\x0c\x12\x1f\n\x17\x45SecureFirmwareRootKey0\x18\n \x01(\x0c\x12\x1c\n\x14HostFirmwareRootKey0\x18\x0b \x01(\x0c\x12\x1f\n\x17\x45SecureFirmwareRootKey1\x18\x0c \x01(\x0c\x12\x1c\n\x14HostFirmwareRootKey1\x18\r \x01(\x0c\x32=\n\x04Keys\x12\x35\n\x0b\x46\x65tchKeySet\x12\x18.keys.FetchKeySetRequest\x1a\x0c.keys.KeySetb\x06proto3')
)




_FETCHKEYSETREQUEST = _descriptor.Descriptor(
  name='FetchKeySetRequest',
  full_name='keys.FetchKeySetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='keys.FetchKeySetRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=52,
)


_KEYSET = _descriptor.Descriptor(
  name='KeySet',
  full_name='keys.KeySet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChipManufacturerPublicKey0', full_name='keys.KeySet.ChipManufacturerPublicKey0', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SystemManufacturerPublicKey0', full_name='keys.KeySet.SystemManufacturerPublicKey0', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChipManufacturerPublicKey1', full_name='keys.KeySet.ChipManufacturerPublicKey1', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SystemManufacturerPublicKey1', full_name='keys.KeySet.SystemManufacturerPublicKey1', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ESecureFirmwareRootKey0', full_name='keys.KeySet.ESecureFirmwareRootKey0', index=4,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HostFirmwareRootKey0', full_name='keys.KeySet.HostFirmwareRootKey0', index=5,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ESecureFirmwareRootKey1', full_name='keys.KeySet.ESecureFirmwareRootKey1', index=6,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HostFirmwareRootKey1', full_name='keys.KeySet.HostFirmwareRootKey1', index=7,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=337,
)

DESCRIPTOR.message_types_by_name['FetchKeySetRequest'] = _FETCHKEYSETREQUEST
DESCRIPTOR.message_types_by_name['KeySet'] = _KEYSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchKeySetRequest = _reflection.GeneratedProtocolMessageType('FetchKeySetRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHKEYSETREQUEST,
  __module__ = 'keys_pb2'
  # @@protoc_insertion_point(class_scope:keys.FetchKeySetRequest)
  ))
_sym_db.RegisterMessage(FetchKeySetRequest)

KeySet = _reflection.GeneratedProtocolMessageType('KeySet', (_message.Message,), dict(
  DESCRIPTOR = _KEYSET,
  __module__ = 'keys_pb2'
  # @@protoc_insertion_point(class_scope:keys.KeySet)
  ))
_sym_db.RegisterMessage(KeySet)



_KEYS = _descriptor.ServiceDescriptor(
  name='Keys',
  full_name='keys.Keys',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=339,
  serialized_end=400,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchKeySet',
    full_name='keys.Keys.FetchKeySet',
    index=0,
    containing_service=None,
    input_type=_FETCHKEYSETREQUEST,
    output_type=_KEYSET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYS)

DESCRIPTOR.services_by_name['Keys'] = _KEYS

# @@protoc_insertion_point(module_scope)
