# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certificates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='certificates.proto',
  package='certificates',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63\x65rtificates.proto\x12\x0c\x63\x65rtificates\"\xb9\x01\n\x14\x45KCertificateRequest\x12\x10\n\x08PublicEK\x18\x01 \x01(\x0c\x12\x13\n\x0bProductName\x18\x02 \x01(\t\x12\x14\n\x0cSerialNumber\x18\x03 \x01(\t\x12\x19\n\x11PrimaryMACAddress\x18\x04 \x01(\t\x12\x12\n\nPartNumber\x18\x0b \x01(\t\x12\x19\n\x11ManufacturingDate\x18\x0c \x01(\t\x12\x0b\n\x03SKU\x18\r \x01(\t\x12\r\n\x05MTPID\x18\x0e \x01(\t\"\"\n\x0b\x43\x65rtificate\x12\x13\n\x0b\x43\x65rtificate\x18\x01 \x01(\x0c\"7\n\x12\x43\x65rtificateRequest\x12!\n\x19\x43\x65rtificateSigningRequest\x18\x01 \x01(\x0c\"*\n\x13\x43\x65rtificateResponse\x12\x13\n\x0b\x43\x65rtificate\x18\x01 \x01(\x0c\x32\xc0\x01\n\x0c\x43\x65rtificates\x12S\n\x12IssueEKCertificate\x12\".certificates.EKCertificateRequest\x1a\x19.certificates.Certificate\x12[\n\x14IssueDICECertificate\x12 .certificates.CertificateRequest\x1a!.certificates.CertificateResponseb\x06proto3'
)




_EKCERTIFICATEREQUEST = _descriptor.Descriptor(
  name='EKCertificateRequest',
  full_name='certificates.EKCertificateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PublicEK', full_name='certificates.EKCertificateRequest.PublicEK', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProductName', full_name='certificates.EKCertificateRequest.ProductName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SerialNumber', full_name='certificates.EKCertificateRequest.SerialNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PrimaryMACAddress', full_name='certificates.EKCertificateRequest.PrimaryMACAddress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PartNumber', full_name='certificates.EKCertificateRequest.PartNumber', index=4,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ManufacturingDate', full_name='certificates.EKCertificateRequest.ManufacturingDate', index=5,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SKU', full_name='certificates.EKCertificateRequest.SKU', index=6,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MTPID', full_name='certificates.EKCertificateRequest.MTPID', index=7,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=222,
)


_CERTIFICATE = _descriptor.Descriptor(
  name='Certificate',
  full_name='certificates.Certificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Certificate', full_name='certificates.Certificate.Certificate', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=258,
)


_CERTIFICATEREQUEST = _descriptor.Descriptor(
  name='CertificateRequest',
  full_name='certificates.CertificateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CertificateSigningRequest', full_name='certificates.CertificateRequest.CertificateSigningRequest', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=315,
)


_CERTIFICATERESPONSE = _descriptor.Descriptor(
  name='CertificateResponse',
  full_name='certificates.CertificateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Certificate', full_name='certificates.CertificateResponse.Certificate', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=359,
)

DESCRIPTOR.message_types_by_name['EKCertificateRequest'] = _EKCERTIFICATEREQUEST
DESCRIPTOR.message_types_by_name['Certificate'] = _CERTIFICATE
DESCRIPTOR.message_types_by_name['CertificateRequest'] = _CERTIFICATEREQUEST
DESCRIPTOR.message_types_by_name['CertificateResponse'] = _CERTIFICATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EKCertificateRequest = _reflection.GeneratedProtocolMessageType('EKCertificateRequest', (_message.Message,), {
  'DESCRIPTOR' : _EKCERTIFICATEREQUEST,
  '__module__' : 'certificates_pb2'
  # @@protoc_insertion_point(class_scope:certificates.EKCertificateRequest)
  })
_sym_db.RegisterMessage(EKCertificateRequest)

Certificate = _reflection.GeneratedProtocolMessageType('Certificate', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATE,
  '__module__' : 'certificates_pb2'
  # @@protoc_insertion_point(class_scope:certificates.Certificate)
  })
_sym_db.RegisterMessage(Certificate)

CertificateRequest = _reflection.GeneratedProtocolMessageType('CertificateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEREQUEST,
  '__module__' : 'certificates_pb2'
  # @@protoc_insertion_point(class_scope:certificates.CertificateRequest)
  })
_sym_db.RegisterMessage(CertificateRequest)

CertificateResponse = _reflection.GeneratedProtocolMessageType('CertificateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATERESPONSE,
  '__module__' : 'certificates_pb2'
  # @@protoc_insertion_point(class_scope:certificates.CertificateResponse)
  })
_sym_db.RegisterMessage(CertificateResponse)



_CERTIFICATES = _descriptor.ServiceDescriptor(
  name='Certificates',
  full_name='certificates.Certificates',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=362,
  serialized_end=554,
  methods=[
  _descriptor.MethodDescriptor(
    name='IssueEKCertificate',
    full_name='certificates.Certificates.IssueEKCertificate',
    index=0,
    containing_service=None,
    input_type=_EKCERTIFICATEREQUEST,
    output_type=_CERTIFICATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IssueDICECertificate',
    full_name='certificates.Certificates.IssueDICECertificate',
    index=1,
    containing_service=None,
    input_type=_CERTIFICATEREQUEST,
    output_type=_CERTIFICATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CERTIFICATES)

DESCRIPTOR.services_by_name['Certificates'] = _CERTIFICATES

# @@protoc_insertion_point(module_scope)
