# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import certificates_pb2 as certificates__pb2


class CertificatesStub(object):
    """SERVICE TO ISSUE MANUFACTURING CERTIFICATES FOR NAPLES CARDS
    A manufacturing certificate contains card identifiers and the public endorsement key (EK)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueEKCertificate = channel.unary_unary(
                '/certificates.Certificates/IssueEKCertificate',
                request_serializer=certificates__pb2.EKCertificateRequest.SerializeToString,
                response_deserializer=certificates__pb2.Certificate.FromString,
                )
        self.IssueDICECertificate = channel.unary_unary(
                '/certificates.Certificates/IssueDICECertificate',
                request_serializer=certificates__pb2.CertificateRequest.SerializeToString,
                response_deserializer=certificates__pb2.CertificateResponse.FromString,
                )


class CertificatesServicer(object):
    """SERVICE TO ISSUE MANUFACTURING CERTIFICATES FOR NAPLES CARDS
    A manufacturing certificate contains card identifiers and the public endorsement key (EK)
    """

    def IssueEKCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueDICECertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CertificatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueEKCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueEKCertificate,
                    request_deserializer=certificates__pb2.EKCertificateRequest.FromString,
                    response_serializer=certificates__pb2.Certificate.SerializeToString,
            ),
            'IssueDICECertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueDICECertificate,
                    request_deserializer=certificates__pb2.CertificateRequest.FromString,
                    response_serializer=certificates__pb2.CertificateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'certificates.Certificates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Certificates(object):
    """SERVICE TO ISSUE MANUFACTURING CERTIFICATES FOR NAPLES CARDS
    A manufacturing certificate contains card identifiers and the public endorsement key (EK)
    """

    @staticmethod
    def IssueEKCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/certificates.Certificates/IssueEKCertificate',
            certificates__pb2.EKCertificateRequest.SerializeToString,
            certificates__pb2.Certificate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IssueDICECertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/certificates.Certificates/IssueDICECertificate',
            certificates__pb2.CertificateRequest.SerializeToString,
            certificates__pb2.CertificateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
