# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import random_pb2 as random__pb2


class RandomStub(object):
    """SERVICE TO GET RANDOM DATA FROM THE HSM
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBytes = channel.unary_unary(
                '/random.Random/GetBytes',
                request_serializer=random__pb2.GetBytesRequest.SerializeToString,
                response_deserializer=random__pb2.Bytes.FromString,
                )


class RandomServicer(object):
    """SERVICE TO GET RANDOM DATA FROM THE HSM
    """

    def GetBytes(self, request, context):
        """GetBytes returns a random bytes string
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBytes,
                    request_deserializer=random__pb2.GetBytesRequest.FromString,
                    response_serializer=random__pb2.Bytes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'random.Random', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Random(object):
    """SERVICE TO GET RANDOM DATA FROM THE HSM
    """

    @staticmethod
    def GetBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/random.Random/GetBytes',
            random__pb2.GetBytesRequest.SerializeToString,
            random__pb2.Bytes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
