# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: random.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='random.proto',
  package='random',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0crandom.proto\x12\x06random\"\x1f\n\x0fGetBytesRequest\x12\x0c\n\x04Size\x18\x01 \x01(\x04\"\x16\n\x05\x42ytes\x12\r\n\x05\x42ytes\x18\x01 \x01(\x0c\x32<\n\x06Random\x12\x32\n\x08GetBytes\x12\x17.random.GetBytesRequest\x1a\r.random.Bytesb\x06proto3'
)




_GETBYTESREQUEST = _descriptor.Descriptor(
  name='GetBytesRequest',
  full_name='random.GetBytesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Size', full_name='random.GetBytesRequest.Size', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_BYTES = _descriptor.Descriptor(
  name='Bytes',
  full_name='random.Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Bytes', full_name='random.Bytes.Bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['GetBytesRequest'] = _GETBYTESREQUEST
DESCRIPTOR.message_types_by_name['Bytes'] = _BYTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBytesRequest = _reflection.GeneratedProtocolMessageType('GetBytesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBYTESREQUEST,
  '__module__' : 'random_pb2'
  # @@protoc_insertion_point(class_scope:random.GetBytesRequest)
  })
_sym_db.RegisterMessage(GetBytesRequest)

Bytes = _reflection.GeneratedProtocolMessageType('Bytes', (_message.Message,), {
  'DESCRIPTOR' : _BYTES,
  '__module__' : 'random_pb2'
  # @@protoc_insertion_point(class_scope:random.Bytes)
  })
_sym_db.RegisterMessage(Bytes)



_RANDOM = _descriptor.ServiceDescriptor(
  name='Random',
  full_name='random.Random',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBytes',
    full_name='random.Random.GetBytes',
    index=0,
    containing_service=None,
    input_type=_GETBYTESREQUEST,
    output_type=_BYTES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANDOM)

DESCRIPTOR.services_by_name['Random'] = _RANDOM

# @@protoc_insertion_point(module_scope)
