#!/bin/sh

cat NAPLES_PMBUS.redis | redis-cli -h 127.0.0.1
cat NAPLES_QSFP.redis | redis-cli -h 127.0.0.1
cat NAPLES_RTC.redis | redis-cli -h 127.0.0.1
cat NAPLES_TEMPSENSOR.redis | redis-cli -h 127.0.0.1

cat NAPLES_DIAGMGR.redis | redis-cli -h 127.0.0.1

