#!/bin/sh

export REDIS_IP="127.0.0.1"
#hostIdx=$(redis-cli -h ${REDIS_IP} -p 6379 INCR HOST_IDX)
#export CARD_TYPE="HOST"${hostIdx}
export CARD_NAME="TOR1"
Lipari=$(cat /proc/cpuinfo | grep AuthenticAMD | wc -l)
if [[ $Lipari == "0" ]]
then
    export CARD_TYPE="TAORMINA"
else
    export CARD_TYPE="LIPARI"
fi
export UUT_TYPE="TOR"
