

---
INFO_GENERAL:
    SUCCESS: 0
    FAIL: -1
    INVALID_PARAM: 1
    SKIP: 2
    TIMEOUT: 3
    INVALID_TEST: 4
    PERM_SKIP: 5
    INVALID_LOCK: 6

INFO_DIAGMGR:
    SKIP: 100
    TIMEOUT: 101
    INVALID_TEST: 102
    PERM_SKIP: 103

INFO_TEMPSENSOR:
    INVALID_ID: 200
    OVER_LIMIT: 201
...
