package errType

const(
    // INFO_GENERAL
    GENERAL_SUCCESS      = 0
    GENERAL_INVALID_PARAM = 1
    GENERAL_FAIL         = -1
    // INFO_DIAGMGR
    DIAGMGR_SKIP         = 100
    DIAGMGR_TIMEOUT      = 101
    DIAGMGR_INVALID_TEST = 102
    DIAGMGR_PERM_SKIP    = 103
)