---
pen-hwlab-apc-01:
    IP: 192.168.70.245
    MODEL: RARITAN
    USR: admin
    PASSWD: lab123

pen-hwlab-apc-02:
    IP: 192.168.72.137
    MODEL: SCHNEIDER
    USR: apc
    PASSWD: apc

pen-chamber-apc-01:
    IP: 192.168.75.40
    MODEL: SCHNEIDER
    USR: apc
    PASSWD: apc

...
