---
MTP001:
    SKIP:
    MODE: MTP_QK
    TS: pen-hwlab-tel-02
    TS_PORT: 2008
    APC_1_NAME: pen-hwlab-apc-02
    APC_1_PORT: 9
    APC_2_NAME:
    APC_2_PORT:
    IP: 192.168.75.205
    SLOT_1:
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: 
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: 

MTP002:
    SKIP:
    MODE: MTP_QK
    TS: pen-hwlab-tel-02
    TS_PORT: 2004
    APC_1_NAME: pen-hwlab-apc-02
    APC_1_PORT: 10
    APC_2_NAME:
    APC_2_PORT:
    IP: 192.168.75.202
    SLOT_1: NAPLES_MTP
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: NAPLES_MTP
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: NAPLES_MTP

MTP003:
    SKIP:
    MODE: MTP_QK
    TS: pen-hwlab-tel-02
    TS_PORT: 2003
    APC_1_NAME: pen-hwlab-apc-02
    APC_1_PORT: 11
    APC_2_NAME: pen-hwlab-apc-02
    APC_2_PORT: 2
    IP: 192.168.72.191
    SLOT_1:
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: 
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: 

MTP004:
    SKIP:
    MODE: MTP_QK
    TS: pen-chamber-01
    TS_PORT: 7001
    APC_1_NAME: pen-chamber-apc-01
    APC_1_PORT: 1
    APC_2_NAME: pen-chamber-apc-01
    APC_2_PORT: 2
    IP: 192.168.73.247
    SLOT_1:
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: 
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: 

MTP024:
    SKIP:
    MODE: MTP_QK
    TS: pen-hwlab-tel-02
    TS_PORT: 2007
    APC_1_NAME: pen-hwlab-apc-03
    APC_1_PORT: 1
    APC_2_NAME: pen-hwlab-apc-03
    APC_2_PORT: 2
    IP: 192.168.72.110
    SLOT_1:
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: 
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: 

MTPS01:
    SKIP:
    MODE: MTP_QK
    TS: pen-hwlab-tel-02
    TS_PORT: 2003
    APC_1_NAME: pen-hwlab-apc-02
    APC_1_PORT: 4
    APC_2_NAME:
    APC_2_PORT:
    IP: 192.168.74.21
    SLOT_1:
    SLOT_2: 
    SLOT_3: 
    SLOT_4: 
    SLOT_5: 
    SLOT_6: 
    SLOT_7: 
    SLOT_8: 
    SLOT_9: 
    SLOT_10: 

...
