MTP-111:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.121"
    APC1_PORT: "1"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.121"
    APC2_PORT: "2"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.119"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp111"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-112:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.121"
    APC1_PORT: "3"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.121"
    APC2_PORT: "4"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.120"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp112"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-113:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.121"
    APC1_PORT: "21"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.121"
    APC2_PORT: "22"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.122"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp113"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-114:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.121"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.121"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.123"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp114"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-115:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.121"
    APC1_PORT: "19"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.121"
    APC2_PORT: "20"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.124"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp115"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-502:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.2.14"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.2.14"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.32"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp502"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-503:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.2.14"
    APC1_PORT: "6"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.2.14"
    APC2_PORT: "7"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.33"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp503"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-504:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.2.14"
    APC1_PORT: "9"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.2.14"
    APC2_PORT: "10"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.34"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp504"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-505:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.2.14"
    APC1_PORT: "11"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.2.14"
    APC2_PORT: "12"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.35"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp505"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-506:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.2.14"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.2.14"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.36"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp505"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-200:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.127"
    APC1_PORT: "10"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.127"
    APC2_PORT: "11"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.130"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp200"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-201:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.127"
    APC1_PORT: "1"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.127"
    APC2_PORT: "2"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.126"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp201"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-204:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.127"
    APC1_PORT: "3"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.127"
    APC2_PORT: "4"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.129"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp204"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-205:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.127"
    APC1_PORT: "5"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.127"
    APC2_PORT: "6"
    APC2_USERID: ""
    APC2_PASSWORD: ""
    IP: "192.168.1.132"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp205"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-206:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.127"
    APC1_PORT: "7"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.127"
    APC2_PORT: "9"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.133"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp206"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-601:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.61"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp601"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-602:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.2.62"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp602"
    SLOTS: 10
    CAPABILITY: 0x2
