# This Yaml File is to define test suite with test case
TEST_SUITE_NAME: "DDR TEST SUITE"
TEST_CASE:
  ########################################## Format Specification ##########################################
  # - NAME: DDR_BIST
  #   ITER: 1 # Will Power cycle card at the begining of each iteration
  #   ITER_PER_PC: 1  # iterations running per each power cycle loop
  # - NAME: POWER_CYCLE_ONLY
  #   ITER: 1
  # - NAME: SNAKE
  #   ITER: 1
  #   ITER_PER_PC: 1
  # - NAME: EDMA#DDR_STRESS  #concatenate multiple test name with hashtag if they share the same iteration parameter, so we will run them together to save a nic re-initinal time
  #   ITER: 10 # keep 1 for EDMA and DDR_STRESS
  #   ITER_PER_PC: 1
  ########################################## Real Instance Below ##########################################
  - NAME: DDR_BIST
    ITER: 10 # Will Power cycle card at the begining of each iteration
    ITER_PER_PC: 1  # iterations running per each power cycle loop
  - NAME: POWER_CYCLE_ONLY
    ITER: 20
  - NAME: SNAKE
    ITER: 10
    ITER_PER_PC: 1
  - NAME: EDMA#DDR_STRESS  #concatenate multiple test name with hashtag if they share the same iteration parameter, so we will run them together to save a nic re-initinal time
    ITER: 1 # keep 1 for EDMA and DDR_STRESS
    ITER_PER_PC: 10
