MTPS-400:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.125"
    APC1_PORT: "23"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: ""
    APC2_PASSWORD: ""
    IP: "192.168.1.139"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtps400"
    SLOTS: 4
    CAPABILITY: 0x3
