MTP-300:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.125"
    APC1_PORT: "1"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.125"
    APC2_PORT: "2"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.140"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp300"
    SLOTS: 10
    CAPABILITY: 0x3
