MTP-004:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-10-17_11-39-00
    NIC-01:
        VALID: "No"
    NIC-02:
        VALID: "Yes"
        SN: "FLM18310001"
        MAC: "00AECD000001"
        TS: 2018-10-17_11-39-12
    NIC-03:
        VALID: "No"
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
