MTP-101:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-10-12_15-26-07
    NIC-01:
        VALID: "No"
    NIC-02:
        VALID: "Yes"
        SN: "FLM18310006"
        MAC: "00AECD000006"
        TS: 2018-10-12_15-26-53
    NIC-03:
        VALID: "No"
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
