MTP-201:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-12-06_10-02-44
    NIC-01:
        VALID: "Yes"
        SN: "FLM18480030"
        MAC: "00AECD001440"
        TS: 120618
    NIC-02:
        VALID: "Yes"
        SN: "FLM18480019"
        MAC: "00AECD001500"
        TS: 120618
    NIC-03:
        VALID: "Yes"
        SN: "FLM18480064"
        MAC: "00AECD0013B0"
        TS: 120618
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
