MTP-003:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-11-16_16-26-25
    NIC-01:
        VALID: "Yes"
        SN: "FLM18111601"
        MAC: "00AECD000001"
        TS: 2018-11-16_16-27-23
    NIC-02:
        VALID: "Yes"
        SN: "FLM18111602"
        MAC: "00AECD000002"
        TS: 2018-11-16_16-27-34
    NIC-03:
        VALID: "Yes"
        SN: "FLM18111603"
        MAC: "00AECD000003"
        TS: 2018-11-16_16-27-45
    NIC-04:
        VALID: "Yes"
        SN: "FLM18111604"
        MAC: "00AECD000004"
        TS: 2018-11-16_16-27-57
    NIC-05:
        VALID: "Yes"
        SN: "FLM18111605"
        MAC: "00AECD000005"
        TS: 2018-11-16_16-28-10
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
