MTP-003:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-11-27_15-25-03
    NIC-01:
        VALID: "No"
    NIC-02:
        VALID: "No"
    NIC-03:
        VALID: "Yes"
        SN: "FLM1842005F"
        MAC: "00AECD001050"
        TS: 2018-11-27_15-25-26
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
