MTP-001:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-09-27_14-24-20
    NIC-01:
        VALID: "Yes"
        SN: "FLM00000000"
        MAC: "00AECD000000"
        TS: 2018-09-27_14-24-31
    NIC-02:
        VALID: "No"
    NIC-03:
        VALID: "No"
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
