MTP-201:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-12-04_18-01-43
    NIC-01:
        VALID: "Yes"
        SN: "FLM18310002"
        MAC: "00AECD000002"
        TS: 120418
    NIC-02:
        VALID: "No"
    NIC-03:
        VALID: "No"
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "No"
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "No"
