MTP-001:
    SRV: PENSANDO-PRO-SRV1
    TS: 2018-10-09_11-33-31
    NIC-01:
        VALID: "Yes"
        SN: "FLM00000001"
        MAC: "00AECD000001"
        TS: 2018-10-09_11-33-48
    NIC-02:
        VALID: "No"
    NIC-03:
        VALID: "No"
    NIC-04:
        VALID: "No"
    NIC-05:
        VALID: "Yes"
        SN: "FLM18400008"
        MAC: "00AECD000408"
        TS: 2018-10-09_11-34-23
    NIC-06:
        VALID: "No"
    NIC-07:
        VALID: "No"
    NIC-08:
        VALID: "No"
    NIC-09:
        VALID: "No"
    NIC-10:
        VALID: "Yes"
        SN: "FLM0000000A"
        MAC: "00AECD00000A"
        TS: 2018-10-09_11-34-38
