# global init command beore diag run
INIT:
    - "Initialize command 1"

SKIP:
    # skip whole dsp
    # - "DSP1#ALL"
    # skip single test of a dsp
    - "DSP2#TEST1"
    # skip multiple tests of a dsp, seperate with '#'
    # - "DSP3#TEST1#TEST2"

PARAMS:
    - "MTP1#ASIC#L1#timeout=5400"

MTP_SEQ:
    ASIC:
        PCIE_PRBS:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: No
                SN: Yes
                SLOT: Yes
        L1:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: No
                SN: Yes
                SLOT: Yes
        ETH_PRBS:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: No
                SN: Yes
                SLOT: Yes
MTP_PARA:
#    DSP:
#        TEST:
#            - INIT: ""
#            - POST: ""
