NAPLES100:
    CPLD_FILE: "/home/diag/naples100_cpld_rev7.bin"
    VRM_FILE:  "/home/diag/naples100_vrm_rev0.bin"
    VRM_CKSUM: 0x55AA
    QSPI_FILE: "/home/diag/naples100_qspi_111518.tar"

NAPLES25:
    CPLD_FILE: "/home/diag/naples25.bin"
    VRM_FILE:  "/home/diag/naples25_vrm.bin"
    VRM_CKSUM: 0x55AA
    QSPI_FILE: "/home/diag/naples25_qspi.tar"

