MTP-001:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.72.137"
    APC2_PORT: "9"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.75.205"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp001"
    SLOTS: 10

MTP-002:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2004"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.72.137"
    APC2_PORT: "20"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.75.202"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp002"
    SLOTS: 10

MTP-003:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2003"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.72.137"
    APC2_PORT: "11"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.72.188"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp003"
    SLOTS: 10

MTP-100:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: "192.168.64.42"
    APC1_PORT: "1"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.64.42"
    APC2_PORT: "2"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.66.200"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp100"
    SLOTS: 10

MTP-101:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2004"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: "192.168.64.42"
    APC1_PORT: "3"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.64.42"
    APC2_PORT: "4"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.66.209"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp101"
    SLOTS: 10

MTP-102:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2003"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: "192.168.64.42"
    APC1_PORT: "5"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.64.42"
    APC2_PORT: "6"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.66.191"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp102"
    SLOTS: 10

