MTP-001:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.70.161"
    APC2_PORT: "12"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.68.182"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp001"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-004:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.72.137"
    APC2_PORT: "23"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.70.123"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp004"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-002:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.70.161"
    APC2_PORT: "19"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.71.61"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp002"
    SLOTS: 10
    CAPABILITY: 0x2

MTP-003:
    MODE: ""
    TS: "192.168.74.208"
    TS_PORT: "2008"
    TS_USERID: "admin"
    TS_PASSWORD: "N0isystem$"
    APC1: "192.168.70.161"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: ""
    APC2_PASSWORD: ""
    IP: "192.168.68.215"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp003"
    SLOTS: 10
    CAPABILITY: 0x1

MTP-020:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.70.161"
    APC2_PORT: "6"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.68.185"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp010"
    SLOTS: 10
    CAPABILITY: 0x1


# Naples100 debug chassis
# Capability: 1=>Naples100; 2=>Naples25; 3=>Both
MTP-098:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.1.114"
    APC2_PORT: "3"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.252"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp098"
    SLOTS: 10
    CAPABILITY: 0x1

# Naples25 debug chassis
MTP-099:
    MODE: ""
    TS: "192.168.1.127"
    TS_PORT: "3"
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: ""
    APC1_PORT: ""
    APC1_USERID: ""
    APC1_PASSWORD: ""
    APC2: "192.168.1.114"
    APC2_PORT: "4"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.251"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp099"
    SLOTS: 10
    CAPABILITY: 0x3

MTPS-001:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.70.161"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: ""
    APC2_PORT: ""
    APC2_USERID: ""
    APC2_PASSWORD: ""
    IP: "192.168.69.136"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtps001"
    SLOTS: 4
    CAPABILITY: 0x3
