###############################
##### Flex Milpitas setup #####
###############################

MTP-301:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.125"
    APC1_PORT: "5"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.125"
    APC2_PORT: "6"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.176"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp301"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-302:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.125"
    APC1_PORT: "7"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.125"
    APC2_PORT: "9"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.177"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp302"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-303:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.1.125"
    APC1_PORT: "3"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.1.125"
    APC2_PORT: "4"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.1.184"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp303"
    SLOTS: 10
    CAPABILITY: 0x3


#############################
##### Flex Penang setup #####
#############################
MTP-200:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.148"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.148"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.59"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp200"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-201:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.148"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.148"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.62"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp201"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-202:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.129"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.129"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.52"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp202"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-203:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.129"
    APC1_PORT: "6"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.129"
    APC2_PORT: "7"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.49"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp203"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-204:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.129"
    APC1_PORT: "11"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.129"
    APC2_PORT: "12"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.47"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp204"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-205:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.46"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp205"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-206:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.129"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.129"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.83"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp206"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-300:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.16"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.16"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.84"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp300"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-310:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.129"
    APC1_PORT: "9"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.129"
    APC2_PORT: "10"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.102"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp310"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-600:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "11"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "12"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.193"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp600"
    SLOTS: 10
    CAPABILITY: 0x3


MTP-653:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.75"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.75"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.137"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp653"
    SLOTS: 10
    CAPABILITY: 0x3

    
MTP-667:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.208"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp667"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-668:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.94"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp668"
    SLOTS: 10
    CAPABILITY: 0x3
    
    
MTP-673:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.184"
    APC1_PORT: "17"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.184"
    APC2_PORT: "18"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.171"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp673"
    SLOTS: 10
    CAPABILITY: 0x3
        
MTP-697:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "9"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "10"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.3"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp697"
    SLOTS: 10
    CAPABILITY: 0x3
    
MTP-698:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.5"
    APC1_PORT: "6"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.5"
    APC2_PORT: "7"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.190"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp698"
    SLOTS: 10
    CAPABILITY: 0x3
   
MTP-715:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.186"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.186"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.200"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp715"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-716:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.186"
    APC1_PORT: "6"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.186"
    APC2_PORT: "7"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.201"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp716"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-717:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.186"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.186"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.199"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp717"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-718:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.75"
    APC1_PORT: "9"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.75"
    APC2_PORT: "10"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.209"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp718"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-719:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.75"
    APC1_PORT: "19"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.75"
    APC2_PORT: "20"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.231"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp719"
    SLOTS: 10
    CAPABILITY: 0x3



MTP-720:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.75"
    APC1_PORT: "21"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.75"
    APC2_PORT: "22"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.210"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp720"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-721:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.16"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.16"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.110"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp721"
    SLOTS: 10
    CAPABILITY: 0x3


MTP-722:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.16"
     APC1_PORT: "6"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.16"
     APC2_PORT: "7"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.204"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp722"
     SLOTS: 10
     CAPABILITY: 0x3

MTP-723:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.16"
     APC1_PORT: "13"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.16"
     APC2_PORT: "14"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.242"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp723"
     SLOTS: 10
     CAPABILITY: 0x3

MTP-724:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.184"
     APC1_PORT: "11"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.184"
     APC2_PORT: "12"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.241"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp724"
     SLOTS: 10
     CAPABILITY: 0x3

MTP-725:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.184"
     APC1_PORT: "13"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.184"
     APC2_PORT: "14"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.240"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp725"
     SLOTS: 10
     CAPABILITY: 0x3

MTP-726:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.129"
     APC1_PORT: "17"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.129"
     APC2_PORT: "18"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.252"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp726"
     SLOTS: 10
     CAPABILITY: 0x3

MTP-800:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.74"
    APC1_PORT: "4"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.74"
    APC2_PORT: "5"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.65"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp800"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-801:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.74"
    APC1_PORT: "6"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.74"
    APC2_PORT: "7"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.64"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp801"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-802:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.74"
    APC1_PORT: "13"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.74"
    APC2_PORT: "14"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.63"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp802"
    SLOTS: 10
    CAPABILITY: 0x3

MTP-803:
    MODE: ""
    TS: ""
    TS_PORT: ""
    TS_USERID: ""
    TS_PASSWORD: ""
    APC1: "192.168.3.148"
    APC1_PORT: "11"
    APC1_USERID: "apc"
    APC1_PASSWORD: "apc"
    APC2: "192.168.3.148"
    APC2_PORT: "12"
    APC2_USERID: "apc"
    APC2_PASSWORD: "apc"
    IP: "192.168.3.82"
    USERID: "diag"
    PASSWORD: "lab123"
    ALIAS: "mtp803"
    SLOTS: 10
    CAPABILITY: 0x3



MTP-675:
     MODE: ""
     TS: ""
     TS_PORT: ""
     TS_USERID: ""
     TS_PASSWORD: ""
     APC1: "192.168.3.14"
     APC1_PORT: "17"
     APC1_USERID: "apc"
     APC1_PASSWORD: "apc"
     APC2: "192.168.3.14"
     APC2_PORT: "18"
     APC2_USERID: "apc"
     APC2_PASSWORD: "apc"
     IP: "192.168.3.173"
     USERID: "diag"
     PASSWORD: "lab123"
     ALIAS: "mtp675"
     SLOTS: 10
     CAPABILITY: 0x3

