# global init command beore diag run
INIT:
    - "Initialize command 1"

SKIP:
    # skip whole dsp
    # - "DSP1#ALL"
    # skip single test of a dsp
    - "DSP2#TEST1"
    # skip multiple tests of a dsp, seperate with '#'
    # - "DSP3#TEST1#TEST2"

PARAMS:
    P2C:
        - "MTP1#ASIC#L1#timeout=4800"
#        - "MTP1#ASIC#L1#zmq_en=1"
        - "MTP1#ASIC#L1#offload=1"
    4C:
        - "MTP1#ASIC#L1#timeout=4800"
#        - "MTP1#ASIC#L1#zmq_en=1"
        - "MTP1#ASIC#L1#offload=1"

MTP_PRE:
    NIC_POWER: True
    NIC_JTAG: True
    NIC_STATUS: True
    NIC_DIAG_BOOT: True
    NIC_CPLD: True

NIC_PARA:
    RTC:
        RTC:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
    EMMC:
        EMMC:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
    QSFP:
        I2C:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
    I2C:
        I2C:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
    NIC_ASIC:
        PCIE_PRBS:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
        ETH_PRBS:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: Yes
                SN: No
                SLOT: No
MTP_PARA:
    SNAKE_HBM: True
    SNAKE_PCIE: True

MTP_SEQ:
    ASIC:
        L1:
            INIT: ""
            POST: ""
            OPTS:
                NIC_NAME: No
                SN: Yes
                SLOT: Yes
                VMARG: Yes

MTP_POST:
    NIC_MEM:  True
