package liparifpga


/*
 * Registers offset
 */

const FPGA1_FPGA_REV_ID_REG            uint64 = 0x0
const FPGA1_FPGA_DATECODE_REG          uint64 = 0x4
const FPGA1_FPGA_TIMECODE_REG          uint64 = 0x8
const FPGA1_BOARD_REV_ID_REG           uint64 = 0xC
const FPGA1_FUNC_CAP_0_REG             uint64 = 0x10
const FPGA1_FUNC_CAP_1_REG             uint64 = 0x14
const FPGA1_FUNC_CAP_2_REG             uint64 = 0x18
const FPGA1_FUNC_CAP_3_REG             uint64 = 0x1C
const FPGA1_FUNC_CAP_4_REG             uint64 = 0x20
const FPGA1_FUNC_CAP_5_REG             uint64 = 0x24
const FPGA1_FUNC_CAP_6_REG             uint64 = 0x28
const FPGA1_FUNC_CAP_7_REG             uint64 = 0x2C
const FPGA1_SCRATCH_0_REG              uint64 = 0x30
const FPGA1_SCRATCH_1_REG              uint64 = 0x34
const FPGA1_SCRATCH_2_REG              uint64 = 0x38
const FPGA1_SCRATCH_3_REG              uint64 = 0x3C
const FPGA1_LED_DEBUG_0_REG            uint64 = 0x40
const FPGA1_LED_DEBUG_1_REG            uint64 = 0x44
const FPGA1_LED_DEBUG_2_REG            uint64 = 0x48
const FPGA1_LED_DEBUG_3_REG            uint64 = 0x4C
const FPGA1_DEBUG_0_REG                uint64 = 0x50
const FPGA1_DEBUG_1_REG                uint64 = 0x54
const FPGA1_DEBUG_2_REG                uint64 = 0x58
const FPGA1_DEBUG_3_REG                uint64 = 0x5C
const FPGA1_INT0_EN_REG                uint64 = 0x60
const FPGA1_INT1_EN_REG                uint64 = 0x64
const FPGA1_INT2_EN_REG                uint64 = 0x68
const FPGA1_INT3_EN_REG                uint64 = 0x6C
const FPGA1_INT4_EN_REG                uint64 = 0x70
const FPGA1_INT5_EN_REG                uint64 = 0x74
const FPGA1_INT6_EN_REG                uint64 = 0x78
const FPGA1_INT7_EN_REG                uint64 = 0x7C
const FPGA1_INT0_PEND_REG              uint64 = 0x80
const FPGA1_INT1_PEND_REG              uint64 = 0x84
const FPGA1_INT2_PEND_REG              uint64 = 0x88
const FPGA1_INT3_PEND_REG              uint64 = 0x8C
const FPGA1_INT4_PEND_REG              uint64 = 0x90
const FPGA1_INT5_PEND_REG              uint64 = 0x94
const FPGA1_INT6_PEND_REG              uint64 = 0x98
const FPGA1_INT7_PEND_REG              uint64 = 0x9C
const FPGA1_BMC_INT0_EN_REG            uint64 = 0xA0
const FPGA1_BMC_INT1_EN_REG            uint64 = 0xA4
const FPGA1_BMC_INT2_EN_REG            uint64 = 0xA8
const FPGA1_BMC_INT3_EN_REG            uint64 = 0xAC
const FPGA1_BMC_INT4_EN_REG            uint64 = 0xB0
const FPGA1_BMC_INT5_EN_REG            uint64 = 0xB4
const FPGA1_BMC_INT6_EN_REG            uint64 = 0xB8
const FPGA1_BMC_INT7_EN_REG            uint64 = 0xBC
const FPGA1_BMC_INT0_PEND_REG          uint64 = 0xC0
const FPGA1_BMC_INT1_PEND_REG          uint64 = 0xC4
const FPGA1_BMC_INT2_PEND_REG          uint64 = 0xC8
const FPGA1_BMC_INT3_PEND_REG          uint64 = 0xCC
const FPGA1_BMC_INT4_PEND_REG          uint64 = 0xD0
const FPGA1_BMC_INT5_PEND_REG          uint64 = 0xD4
const FPGA1_BMC_INT6_PEND_REG          uint64 = 0xD8
const FPGA1_BMC_INT7_PEND_REG          uint64 = 0xDC
const FPGA1_ELBA_RESET_CAUSE_0_REG     uint64 = 0x100
const FPGA1_ELBA_RESET_CAUSE_1_REG     uint64 = 0x104
const FPGA1_ELBA_RESET_CAUSE_2_REG     uint64 = 0x108
const FPGA1_ELBA_RESET_CAUSE_3_REG     uint64 = 0x10C
const FPGA1_ELBA_RESET_CAUSE_4_REG     uint64 = 0x110
const FPGA1_ELBA_RESET_CAUSE_5_REG     uint64 = 0x114
const FPGA1_ELBA_RESET_CAUSE_6_REG     uint64 = 0x118
const FPGA1_ELBA_RESET_CAUSE_7_REG     uint64 = 0x11C
const FPGA1_FPGA_RECONFIG_CTRL_REG     uint64 = 0x120
const FPGA1_FPGA_RECONFIG_STAT_REG     uint64 = 0x124
const FPGA1_MBOX_STAT_REG              uint64 = 0x180
const FPGA1_MBOX_STAT_PLRTY_REG        uint64 = 0x184
const FPGA1_MBOX_STAT_EDG_LVL_REG      uint64 = 0x188
const FPGA1_MBOX_STAT_INT_EN_REG       uint64 = 0x18C
const FPGA1_MBOX_STAT_INT_STAT_REG     uint64 = 0x190
const FPGA1_MBOX_STAT_INT_CLR_REG      uint64 = 0x194
const FPGA1_MBOX_0_DATA_REG            uint64 = 0x198
const FPGA1_MBOX_1_DATA_REG            uint64 = 0x19C
const FPGA1_MBOX_2_DATA_REG            uint64 = 0x1A0
const FPGA1_MBOX_3_DATA_REG            uint64 = 0x1A4
const FPGA1_SOFT_RESET_REG             uint64 = 0x1A8
const FPGA1_MISC_CTRL_REG              uint64 = 0x1AC
const FPGA1_MISC_STAT_REG              uint64 = 0x1B0
const FPGA1_FLSH_CTRL_REG              uint64 = 0x1B4
const FPGA1_ELBA0_CTRL_REG             uint64 = 0x200
const FPGA1_ELBA0_STAT_REG             uint64 = 0x204
const FPGA1_ELBA0_WDOG_CTRL_REG        uint64 = 0x208
const FPGA1_ELBA0_WDOG_STAT_REG        uint64 = 0x20C
const FPGA1_ELBA1_CTRL_REG             uint64 = 0x220
const FPGA1_ELBA1_STAT_REG             uint64 = 0x224
const FPGA1_ELBA1_WDOG_CTRL_REG        uint64 = 0x228
const FPGA1_ELBA1_WDOG_STAT_REG        uint64 = 0x22C
const FPGA1_ELBA2_CTRL_REG             uint64 = 0x240
const FPGA1_ELBA2_STAT_REG             uint64 = 0x244
const FPGA1_ELBA2_WDOG_CTRL_REG        uint64 = 0x248
const FPGA1_ELBA2_WDOG_STAT_REG        uint64 = 0x24C
const FPGA1_ELBA3_CTRL_REG             uint64 = 0x260
const FPGA1_ELBA3_STAT_REG             uint64 = 0x264
const FPGA1_ELBA3_WDOG_CTRL_REG        uint64 = 0x268
const FPGA1_ELBA3_WDOG_STAT_REG        uint64 = 0x26C
const FPGA1_ELBA4_CTRL_REG             uint64 = 0x280
const FPGA1_ELBA4_STAT_REG             uint64 = 0x284
const FPGA1_ELBA4_WDOG_CTRL_REG        uint64 = 0x288
const FPGA1_ELBA4_WDOG_STAT_REG        uint64 = 0x28C
const FPGA1_ELBA5_CTRL_REG             uint64 = 0x2A0
const FPGA1_ELBA5_STAT_REG             uint64 = 0x2A4
const FPGA1_ELBA5_WDOG_CTRL_REG        uint64 = 0x2A8
const FPGA1_ELBA5_WDOG_STAT_REG        uint64 = 0x2AC
const FPGA1_ELBA6_CTRL_REG             uint64 = 0x2C0
const FPGA1_ELBA6_STAT_REG             uint64 = 0x2C4
const FPGA1_ELBA6_WDOG_CTRL_REG        uint64 = 0x2C8
const FPGA1_ELBA6_WDOG_STAT_REG        uint64 = 0x2CC
const FPGA1_ELBA7_CTRL_REG             uint64 = 0x2E0
const FPGA1_ELBA7_STAT_REG             uint64 = 0x2E4
const FPGA1_ELBA7_WDOG_CTRL_REG        uint64 = 0x2E8
const FPGA1_ELBA7_WDOG_STAT_REG        uint64 = 0x2EC
const FPGA1_SPI0_RXDATA_REG            uint64 = 0x300       //SPI0 = FPGA FLASH
const FPGA1_SPI0_TXDATA4B_REG          uint64 = 0x304
const FPGA1_SPI0_TXDATA2B_REG          uint64 = 0x308
const FPGA1_SPI0_TXDATA1B_REG          uint64 = 0x30C
const FPGA1_SPI0_STATUS_REG            uint64 = 0x310
const FPGA1_SPI0_CONTROL_REG           uint64 = 0x314
const FPGA1_SPI0_SEM_REG               uint64 = 0x318
const FPGA1_SPI0_SLAVESEL_REG          uint64 = 0x31C
const FPGA1_SPI0_EOP_VALUE_REG         uint64 = 0x320
const FPGA1_SPI0_MUXSEL_REG            uint64 = 0x324
const FPGA1_SPI1_RXDATA_REG            uint64 = 0x400       //SPI1 - SPI9 = ELBA0 QSPI - ELBA7 QSPI
const FPGA1_SPI1_TXDATA4B_REG          uint64 = 0x404
const FPGA1_SPI1_TXDATA2B_REG          uint64 = 0x408
const FPGA1_SPI1_TXDATA1B_REG          uint64 = 0x40C
const FPGA1_SPI1_STATUS_REG            uint64 = 0x410
const FPGA1_SPI1_CONTROL_REG           uint64 = 0x414
const FPGA1_SPI1_SEM_REG               uint64 = 0x418
const FPGA1_SPI1_SLAVESEL_REG          uint64 = 0x41C
const FPGA1_SPI1_EOP_VALUE_REG         uint64 = 0x420
const FPGA1_SPI1_MUXSEL_REG            uint64 = 0x424
const FPGA1_SPI2_RXDATA_REG            uint64 = 0x440
const FPGA1_SPI2_TXDATA4B_REG          uint64 = 0x444
const FPGA1_SPI2_TXDATA2B_REG          uint64 = 0x448
const FPGA1_SPI2_TXDATA1B_REG          uint64 = 0x44C
const FPGA1_SPI2_STATUS_REG            uint64 = 0x450
const FPGA1_SPI2_CONTROL_REG           uint64 = 0x454
const FPGA1_SPI2_SEM_REG               uint64 = 0x458
const FPGA1_SPI2_SLAVESEL_REG          uint64 = 0x45C
const FPGA1_SPI2_EOP_VALUE_REG         uint64 = 0x460
const FPGA1_SPI2_MUXSEL_REG            uint64 = 0x464
const FPGA1_SPI3_RXDATA_REG            uint64 = 0x480
const FPGA1_SPI3_TXDATA4B_REG          uint64 = 0x484
const FPGA1_SPI3_TXDATA2B_REG          uint64 = 0x488
const FPGA1_SPI3_TXDATA1B_REG          uint64 = 0x48C
const FPGA1_SPI3_STATUS_REG            uint64 = 0x490
const FPGA1_SPI3_CONTROL_REG           uint64 = 0x494
const FPGA1_SPI3_SEM_REG               uint64 = 0x498
const FPGA1_SPI3_SLAVESEL_REG          uint64 = 0x49C
const FPGA1_SPI3_EOP_VALUE_REG         uint64 = 0x4A0
const FPGA1_SPI3_MUXSEL_REG            uint64 = 0x4A4
const FPGA1_SPI4_RXDATA_REG            uint64 = 0x4C0
const FPGA1_SPI4_TXDATA4B_REG          uint64 = 0x4C4
const FPGA1_SPI4_TXDATA2B_REG          uint64 = 0x4C8
const FPGA1_SPI4_TXDATA1B_REG          uint64 = 0x4CC
const FPGA1_SPI4_STATUS_REG            uint64 = 0x4D0
const FPGA1_SPI4_CONTROL_REG           uint64 = 0x4D4
const FPGA1_SPI4_SEM_REG               uint64 = 0x4D8
const FPGA1_SPI4_SLAVESEL_REG          uint64 = 0x4DC
const FPGA1_SPI4_EOP_VALUE_REG         uint64 = 0x4E0
const FPGA1_SPI4_MUXSEL_REG            uint64 = 0x4E4
const FPGA1_SPI5_RXDATA_REG            uint64 = 0x500
const FPGA1_SPI5_TXDATA4B_REG          uint64 = 0x504
const FPGA1_SPI5_TXDATA2B_REG          uint64 = 0x508
const FPGA1_SPI5_TXDATA1B_REG          uint64 = 0x50C
const FPGA1_SPI5_STATUS_REG            uint64 = 0x510
const FPGA1_SPI5_CONTROL_REG           uint64 = 0x514
const FPGA1_SPI5_SEM_REG               uint64 = 0x518
const FPGA1_SPI5_SLAVESEL_REG          uint64 = 0x51C
const FPGA1_SPI5_EOP_VALUE_REG         uint64 = 0x520
const FPGA1_SPI5_MUXSEL_REG            uint64 = 0x524
const FPGA1_SPI6_RXDATA_REG            uint64 = 0x540
const FPGA1_SPI6_TXDATA4B_REG          uint64 = 0x544
const FPGA1_SPI6_TXDATA2B_REG          uint64 = 0x548
const FPGA1_SPI6_TXDATA1B_REG          uint64 = 0x54C
const FPGA1_SPI6_STATUS_REG            uint64 = 0x550
const FPGA1_SPI6_CONTROL_REG           uint64 = 0x554
const FPGA1_SPI6_SEM_REG               uint64 = 0x558
const FPGA1_SPI6_SLAVESEL_REG          uint64 = 0x55C
const FPGA1_SPI6_EOP_VALUE_REG         uint64 = 0x560
const FPGA1_SPI6_MUXSEL_REG            uint64 = 0x564
const FPGA1_SPI7_RXDATA_REG            uint64 = 0x580
const FPGA1_SPI7_TXDATA4B_REG          uint64 = 0x584
const FPGA1_SPI7_TXDATA2B_REG          uint64 = 0x588
const FPGA1_SPI7_TXDATA1B_REG          uint64 = 0x58C
const FPGA1_SPI7_STATUS_REG            uint64 = 0x590
const FPGA1_SPI7_CONTROL_REG           uint64 = 0x594
const FPGA1_SPI7_SEM_REG               uint64 = 0x598
const FPGA1_SPI7_SLAVESEL_REG          uint64 = 0x59C
const FPGA1_SPI7_EOP_VALUE_REG         uint64 = 0x5A0
const FPGA1_SPI7_MUXSEL_REG            uint64 = 0x5A4
const FPGA1_SPI8_RXDATA_REG            uint64 = 0x5C0
const FPGA1_SPI8_TXDATA4B_REG          uint64 = 0x5C4
const FPGA1_SPI8_TXDATA2B_REG          uint64 = 0x5C8
const FPGA1_SPI8_TXDATA1B_REG          uint64 = 0x5CC
const FPGA1_SPI8_STATUS_REG            uint64 = 0x5D0
const FPGA1_SPI8_CONTROL_REG           uint64 = 0x5D4
const FPGA1_SPI8_SEM_REG               uint64 = 0x5D8
const FPGA1_SPI8_SLAVESEL_REG          uint64 = 0x5DC
const FPGA1_SPI8_EOP_VALUE_REG         uint64 = 0x5E0
const FPGA1_SPI8_MUXSEL_REG            uint64 = 0x5E4
const FPGA1_SPI9_RXDATA_REG            uint64 = 0x600   //SPI9-16 --> ELBA0 CPLD SPI - ELBA7 CPLD
const FPGA1_SPI9_TXDATA4B_REG          uint64 = 0x604
const FPGA1_SPI9_TXDATA2B_REG          uint64 = 0x608
const FPGA1_SPI9_TXDATA1B_REG          uint64 = 0x60C
const FPGA1_SPI9_STATUS_REG            uint64 = 0x610
const FPGA1_SPI9_CONTROL_REG           uint64 = 0x614
const FPGA1_SPI9_SEM_REG               uint64 = 0x618
const FPGA1_SPI9_SLAVESEL_REG          uint64 = 0x61C
const FPGA1_SPI9_EOP_VALUE_REG         uint64 = 0x620
const FPGA1_SPI9_MUXSEL_REG            uint64 = 0x624
const FPGA1_SPI10_RXDATA_REG           uint64 = 0x640
const FPGA1_SPI10_TXDATA4B_REG         uint64 = 0x644
const FPGA1_SPI10_TXDATA2B_REG         uint64 = 0x648
const FPGA1_SPI10_TXDATA1B_REG         uint64 = 0x64C
const FPGA1_SPI10_STATUS_REG           uint64 = 0x650
const FPGA1_SPI10_CONTROL_REG          uint64 = 0x654
const FPGA1_SPI10_SEM_REG              uint64 = 0x658
const FPGA1_SPI10_SLAVESEL_REG         uint64 = 0x65C
const FPGA1_SPI10_EOP_VALUE_REG        uint64 = 0x660
const FPGA1_SPI10_MUXSEL_REG           uint64 = 0x664
const FPGA1_SPI11_RXDATA_REG           uint64 = 0x680
const FPGA1_SPI11_TXDATA4B_REG         uint64 = 0x684
const FPGA1_SPI11_TXDATA2B_REG         uint64 = 0x688
const FPGA1_SPI11_TXDATA1B_REG         uint64 = 0x68C
const FPGA1_SPI11_STATUS_REG           uint64 = 0x690
const FPGA1_SPI11_CONTROL_REG          uint64 = 0x694
const FPGA1_SPI11_SEM_REG              uint64 = 0x698
const FPGA1_SPI11_SLAVESEL_REG         uint64 = 0x69C
const FPGA1_SPI11_EOP_VALUE_REG        uint64 = 0x6A0
const FPGA1_SPI11_MUXSEL_REG           uint64 = 0x6A4
const FPGA1_SPI12_RXDATA_REG           uint64 = 0x6C0
const FPGA1_SPI12_TXDATA4B_REG         uint64 = 0x6C4
const FPGA1_SPI12_TXDATA2B_REG         uint64 = 0x6C8
const FPGA1_SPI12_TXDATA1B_REG         uint64 = 0x6CC
const FPGA1_SPI12_STATUS_REG           uint64 = 0x6D0
const FPGA1_SPI12_CONTROL_REG          uint64 = 0x6D4
const FPGA1_SPI12_SEM_REG              uint64 = 0x6D8
const FPGA1_SPI12_SLAVESEL_REG         uint64 = 0x6DC
const FPGA1_SPI12_EOP_VALUE_REG        uint64 = 0x6E0
const FPGA1_SPI12_MUXSEL_REG           uint64 = 0x6E4
const FPGA1_SPI13_RXDATA_REG           uint64 = 0x700
const FPGA1_SPI13_TXDATA4B_REG         uint64 = 0x704
const FPGA1_SPI13_TXDATA2B_REG         uint64 = 0x708
const FPGA1_SPI13_TXDATA1B_REG         uint64 = 0x70C
const FPGA1_SPI13_STATUS_REG           uint64 = 0x710
const FPGA1_SPI13_CONTROL_REG          uint64 = 0x714
const FPGA1_SPI13_SEM_REG              uint64 = 0x718
const FPGA1_SPI13_SLAVESEL_REG         uint64 = 0x71C
const FPGA1_SPI13_EOP_VALUE_REG        uint64 = 0x720
const FPGA1_SPI13_MUXSEL_REG           uint64 = 0x724
const FPGA1_SPI14_RXDATA_REG           uint64 = 0x740
const FPGA1_SPI14_TXDATA4B_REG         uint64 = 0x744
const FPGA1_SPI14_TXDATA2B_REG         uint64 = 0x748
const FPGA1_SPI14_TXDATA1B_REG         uint64 = 0x74C
const FPGA1_SPI14_STATUS_REG           uint64 = 0x750
const FPGA1_SPI14_CONTROL_REG          uint64 = 0x754
const FPGA1_SPI14_SEM_REG              uint64 = 0x758
const FPGA1_SPI14_SLAVESEL_REG         uint64 = 0x75C
const FPGA1_SPI14_EOP_VALUE_REG        uint64 = 0x760
const FPGA1_SPI14_MUXSEL_REG           uint64 = 0x764
const FPGA1_SPI15_RXDATA_REG           uint64 = 0x780
const FPGA1_SPI15_TXDATA4B_REG         uint64 = 0x784
const FPGA1_SPI15_TXDATA2B_REG         uint64 = 0x788
const FPGA1_SPI15_TXDATA1B_REG         uint64 = 0x78C
const FPGA1_SPI15_STATUS_REG           uint64 = 0x790
const FPGA1_SPI15_CONTROL_REG          uint64 = 0x794
const FPGA1_SPI15_SEM_REG              uint64 = 0x798
const FPGA1_SPI15_SLAVESEL_REG         uint64 = 0x79C
const FPGA1_SPI15_EOP_VALUE_REG        uint64 = 0x7A0
const FPGA1_SPI15_MUXSEL_REG           uint64 = 0x7A4
const FPGA1_SPI16_RXDATA_REG           uint64 = 0x7C0
const FPGA1_SPI16_TXDATA4B_REG         uint64 = 0x7C4
const FPGA1_SPI16_TXDATA2B_REG         uint64 = 0x7C8
const FPGA1_SPI16_TXDATA1B_REG         uint64 = 0x7CC
const FPGA1_SPI16_STATUS_REG           uint64 = 0x7D0
const FPGA1_SPI16_CONTROL_REG          uint64 = 0x7D4
const FPGA1_SPI16_SEM_REG              uint64 = 0x7D8
const FPGA1_SPI16_SLAVESEL_REG         uint64 = 0x7DC
const FPGA1_SPI16_EOP_VALUE_REG        uint64 = 0x7E0
const FPGA1_SPI16_MUXSEL_REG           uint64 = 0x7E4
const FPGA1_I2C_CH0_PRSCL_LO_REG       uint64 = 0x800
const FPGA1_I2C_CH0_PRSCL_HI_REG       uint64 = 0x804
const FPGA1_I2C_CH0_CTRL_REG           uint64 = 0x808
const FPGA1_I2C_CH0_TX_REG             uint64 = 0x80C
const FPGA1_I2C_CH0_RX_REG             uint64 = 0x80C
const FPGA1_I2C_CH0_CMD_REG            uint64 = 0x810
const FPGA1_I2C_CH0_STAT_REG           uint64 = 0x810
const FPGA1_I2C_CH0_MUX_SEL_REG        uint64 = 0x814
const FPGA1_I2C_CH0_RST_REG            uint64 = 0x818
const FPGA1_I2C_CH0_SEM_REG            uint64 = 0x81C
const FPGA1_I2C_CH1_PRSCL_LO_REG       uint64 = 0x840
const FPGA1_I2C_CH1_PRSCL_HI_REG       uint64 = 0x844
const FPGA1_I2C_CH1_CTRL_REG           uint64 = 0x848
const FPGA1_I2C_CH1_TX_REG             uint64 = 0x84C
const FPGA1_I2C_CH1_RX_REG             uint64 = 0x84C
const FPGA1_I2C_CH1_CMD_REG            uint64 = 0x850
const FPGA1_I2C_CH1_STAT_REG           uint64 = 0x850
const FPGA1_I2C_CH1_MUX_SEL_REG        uint64 = 0x854
const FPGA1_I2C_CH1_RST_REG            uint64 = 0x858
const FPGA1_I2C_CH1_SEM_REG            uint64 = 0x85C
const FPGA1_ELBA0_J2C_CMD_REG          uint64 = 0xA00
const FPGA1_ELBA0_J2C_STAT_REG         uint64 = 0xA04
const FPGA1_ELBA0_J2C_ADDR0_REG        uint64 = 0xA08
const FPGA1_ELBA0_J2C_ADDR1_REG        uint64 = 0xA0C
const FPGA1_ELBA0_J2C_TXDATA_REG       uint64 = 0xA10
const FPGA1_ELBA0_J2C_RXDATA_REG       uint64 = 0xA14
const FPGA1_ELBA1_J2C_CMD_REG          uint64 = 0xA20
const FPGA1_ELBA1_J2C_STAT_REG         uint64 = 0xA24
const FPGA1_ELBA1_J2C_ADDR0_REG        uint64 = 0xA28
const FPGA1_ELBA1_J2C_ADDR1_REG        uint64 = 0xA2C
const FPGA1_ELBA1_J2C_TXDATA_REG       uint64 = 0xA30
const FPGA1_ELBA1_J2C_RXDATA_REG       uint64 = 0xA34
const FPGA1_ELBA2_J2C_CMD_REG          uint64 = 0xA40
const FPGA1_ELBA2_J2C_STAT_REG         uint64 = 0xA44
const FPGA1_ELBA2_J2C_ADDR0_REG        uint64 = 0xA48
const FPGA1_ELBA2_J2C_ADDR1_REG        uint64 = 0xA4C
const FPGA1_ELBA2_J2C_TXDATA_REG       uint64 = 0xA50
const FPGA1_ELBA2_J2C_RXDATA_REG       uint64 = 0xA54
const FPGA1_ELBA3_J2C_CMD_REG          uint64 = 0xA60
const FPGA1_ELBA3_J2C_STAT_REG         uint64 = 0xA64
const FPGA1_ELBA3_J2C_ADDR0_REG        uint64 = 0xA68
const FPGA1_ELBA3_J2C_ADDR1_REG        uint64 = 0xA6C
const FPGA1_ELBA3_J2C_TXDATA_REG       uint64 = 0xA70
const FPGA1_ELBA3_J2C_RXDATA_REG       uint64 = 0xA74
const FPGA1_ELBA4_J2C_CMD_REG          uint64 = 0xA80
const FPGA1_ELBA4_J2C_STAT_REG         uint64 = 0xA84
const FPGA1_ELBA4_J2C_ADDR0_REG        uint64 = 0xA88
const FPGA1_ELBA4_J2C_ADDR1_REG        uint64 = 0xA8C
const FPGA1_ELBA4_J2C_TXDATA_REG       uint64 = 0xA90
const FPGA1_ELBA4_J2C_RXDATA_REG       uint64 = 0xA94
const FPGA1_ELBA5_J2C_CMD_REG          uint64 = 0xAA0
const FPGA1_ELBA5_J2C_STAT_REG         uint64 = 0xAA4
const FPGA1_ELBA5_J2C_ADDR0_REG        uint64 = 0xAA8
const FPGA1_ELBA5_J2C_ADDR1_REG        uint64 = 0xAAC
const FPGA1_ELBA5_J2C_TXDATA_REG       uint64 = 0xAB0
const FPGA1_ELBA5_J2C_RXDATA_REG       uint64 = 0xAB4
const FPGA1_ELBA6_J2C_CMD_REG          uint64 = 0xAC0
const FPGA1_ELBA6_J2C_STAT_REG         uint64 = 0xAC4
const FPGA1_ELBA6_J2C_ADDR0_REG        uint64 = 0xAC8
const FPGA1_ELBA6_J2C_ADDR1_REG        uint64 = 0xACC
const FPGA1_ELBA6_J2C_TXDATA_REG       uint64 = 0xAD0
const FPGA1_ELBA6_J2C_RXDATA_REG       uint64 = 0xAD4
const FPGA1_ELBA7_J2C_CMD_REG          uint64 = 0xAE0
const FPGA1_ELBA7_J2C_STAT_REG         uint64 = 0xAE4
const FPGA1_ELBA7_J2C_ADDR0_REG        uint64 = 0xAE8
const FPGA1_ELBA7_J2C_ADDR1_REG        uint64 = 0xAEC
const FPGA1_ELBA7_J2C_TXDATA_REG       uint64 = 0xAF0
const FPGA1_ELBA7_J2C_RXDATA_REG       uint64 = 0xAF4
const FPGA1_RTC_CLOCK_REG              uint64 = 0xC00
const FPGA1_RTC_TIMER_REG              uint64 = 0xC04
const FPGA1_RTC_STPWTCH_REG            uint64 = 0xC08
const FPGA1_RTC_ALARM_REG              uint64 = 0xC0C
const FPGA1_RTC_CKSPEED_REG            uint64 = 0xC10
const FPGA1_RTC_HACKTIME_REG           uint64 = 0xC14
const FPGA1_RTC_HACKCNTHI_REG          uint64 = 0xC18
const FPGA1_RTC_HACKCNTLO_REG          uint64 = 0xC1C
const FPGA1_RTC_DATE_REG               uint64 = 0xC20
const FPGA_ELBA0_UART_RXDATA_REG       uint64 = 0x1000
const FPGA_ELBA0_UART_TXDATA_REG       uint64 = 0x1004
const FPGA_ELBA0_UART_STAT_REG         uint64 = 0x1008
const FPGA_ELBA0_UART_CTRL_REG         uint64 = 0x100C
const FPGA_ELBA1_UART_RXDATA_REG       uint64 = 0x1100
const FPGA_ELBA1_UART_TXDATA_REG       uint64 = 0x1104
const FPGA_ELBA1_UART_STAT_REG         uint64 = 0x1108
const FPGA_ELBA1_UART_CTRL_REG         uint64 = 0x110C
const FPGA_ELBA2_UART_RXDATA_REG       uint64 = 0x1200
const FPGA_ELBA2_UART_TXDATA_REG       uint64 = 0x1204
const FPGA_ELBA2_UART_STAT_REG         uint64 = 0x1208
const FPGA_ELBA2_UART_CTRL_REG         uint64 = 0x120C
const FPGA_ELBA3_UART_RXDATA_REG       uint64 = 0x1300
const FPGA_ELBA3_UART_TXDATA_REG       uint64 = 0x1304
const FPGA_ELBA3_UART_STAT_REG         uint64 = 0x1308
const FPGA_ELBA3_UART_CTRL_REG         uint64 = 0x130C
const FPGA_ELBA4_UART_RXDATA_REG       uint64 = 0x1400
const FPGA_ELBA4_UART_TXDATA_REG       uint64 = 0x1404
const FPGA_ELBA4_UART_STAT_REG         uint64 = 0x1408
const FPGA_ELBA4_UART_CTRL_REG         uint64 = 0x140C
const FPGA_ELBA5_UART_RXDATA_REG       uint64 = 0x1500
const FPGA_ELBA5_UART_TXDATA_REG       uint64 = 0x1504
const FPGA_ELBA5_UART_STAT_REG         uint64 = 0x1508
const FPGA_ELBA5_UART_CTRL_REG         uint64 = 0x150C
const FPGA_ELBA6_UART_RXDATA_REG       uint64 = 0x1600
const FPGA_ELBA6_UART_TXDATA_REG       uint64 = 0x1604
const FPGA_ELBA6_UART_STAT_REG         uint64 = 0x1608
const FPGA_ELBA6_UART_CTRL_REG         uint64 = 0x160C
const FPGA_ELBA7_UART_RXDATA_REG       uint64 = 0x1700
const FPGA_ELBA7_UART_TXDATA_REG       uint64 = 0x1704
const FPGA_ELBA7_UART_STAT_REG         uint64 = 0x1708
const FPGA_ELBA7_UART_CTRL_REG         uint64 = 0x170C

var LIPARI_FPGA1_REGISTERS = []LIPARI_FPGA_REGISTERS {
    LIPARI_FPGA_REGISTERS{"FPGA1_FPGA_REV_ID_REG   ",             FPGA1_FPGA_REV_ID_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FPGA_DATECODE_REG ",             FPGA1_FPGA_DATECODE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FPGA_TIMECODE_REG ",             FPGA1_FPGA_TIMECODE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BOARD_REV_ID_REG  ",             FPGA1_BOARD_REV_ID_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_0_REG    ",             FPGA1_FUNC_CAP_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_1_REG    ",             FPGA1_FUNC_CAP_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_2_REG    ",             FPGA1_FUNC_CAP_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_3_REG    ",             FPGA1_FUNC_CAP_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_4_REG    ",             FPGA1_FUNC_CAP_4_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_5_REG    ",             FPGA1_FUNC_CAP_5_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_6_REG    ",             FPGA1_FUNC_CAP_6_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FUNC_CAP_7_REG    ",             FPGA1_FUNC_CAP_7_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SCRATCH_0_REG     ",             FPGA1_SCRATCH_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SCRATCH_1_REG     ",             FPGA1_SCRATCH_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SCRATCH_2_REG     ",             FPGA1_SCRATCH_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SCRATCH_3_REG     ",             FPGA1_SCRATCH_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_LED_DEBUG_0_REG   ",             FPGA1_LED_DEBUG_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_LED_DEBUG_1_REG   ",             FPGA1_LED_DEBUG_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_LED_DEBUG_2_REG   ",             FPGA1_LED_DEBUG_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_LED_DEBUG_3_REG   ",             FPGA1_LED_DEBUG_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_DEBUG_0_REG       ",             FPGA1_DEBUG_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_DEBUG_1_REG       ",             FPGA1_DEBUG_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_DEBUG_2_REG       ",             FPGA1_DEBUG_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_DEBUG_3_REG       ",             FPGA1_DEBUG_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT0_EN_REG       ",             FPGA1_INT0_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT1_EN_REG       ",             FPGA1_INT1_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT2_EN_REG       ",             FPGA1_INT2_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT3_EN_REG       ",             FPGA1_INT3_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT4_EN_REG       ",             FPGA1_INT4_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT5_EN_REG       ",             FPGA1_INT5_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT6_EN_REG       ",             FPGA1_INT6_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT7_EN_REG       ",             FPGA1_INT7_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT0_PEND_REG     ",             FPGA1_INT0_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT1_PEND_REG     ",             FPGA1_INT1_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT2_PEND_REG     ",             FPGA1_INT2_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT3_PEND_REG     ",             FPGA1_INT3_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT4_PEND_REG     ",             FPGA1_INT4_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT5_PEND_REG     ",             FPGA1_INT5_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT6_PEND_REG     ",             FPGA1_INT6_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_INT7_PEND_REG     ",             FPGA1_INT7_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT0_EN_REG   ",             FPGA1_BMC_INT0_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT1_EN_REG   ",             FPGA1_BMC_INT1_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT2_EN_REG   ",             FPGA1_BMC_INT2_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT3_EN_REG   ",             FPGA1_BMC_INT3_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT4_EN_REG   ",             FPGA1_BMC_INT4_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT5_EN_REG   ",             FPGA1_BMC_INT5_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT6_EN_REG   ",             FPGA1_BMC_INT6_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT7_EN_REG   ",             FPGA1_BMC_INT7_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT0_PEND_REG ",             FPGA1_BMC_INT0_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT1_PEND_REG ",             FPGA1_BMC_INT1_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT2_PEND_REG ",             FPGA1_BMC_INT2_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT3_PEND_REG ",             FPGA1_BMC_INT3_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT4_PEND_REG ",             FPGA1_BMC_INT4_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT5_PEND_REG ",             FPGA1_BMC_INT5_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT6_PEND_REG ",             FPGA1_BMC_INT6_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_BMC_INT7_PEND_REG ",             FPGA1_BMC_INT7_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_0_REG",             FPGA1_ELBA_RESET_CAUSE_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_1_REG",             FPGA1_ELBA_RESET_CAUSE_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_2_REG",             FPGA1_ELBA_RESET_CAUSE_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_3_REG",             FPGA1_ELBA_RESET_CAUSE_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_4_REG",             FPGA1_ELBA_RESET_CAUSE_4_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_5_REG",             FPGA1_ELBA_RESET_CAUSE_5_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_6_REG",             FPGA1_ELBA_RESET_CAUSE_6_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA_RESET_CAUSE_7_REG",             FPGA1_ELBA_RESET_CAUSE_7_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FPGA_RECONFIG_CTRL_REG",             FPGA1_FPGA_RECONFIG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FPGA_RECONFIG_STAT_REG",             FPGA1_FPGA_RECONFIG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_REG     ",             FPGA1_MBOX_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_PLRTY_REG",             FPGA1_MBOX_STAT_PLRTY_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_EDG_LVL_REG",             FPGA1_MBOX_STAT_EDG_LVL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_INT_EN_REG",             FPGA1_MBOX_STAT_INT_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_INT_STAT_REG",             FPGA1_MBOX_STAT_INT_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_STAT_INT_CLR_REG",             FPGA1_MBOX_STAT_INT_CLR_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_0_DATA_REG   ",             FPGA1_MBOX_0_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_1_DATA_REG   ",             FPGA1_MBOX_1_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_2_DATA_REG   ",             FPGA1_MBOX_2_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MBOX_3_DATA_REG   ",             FPGA1_MBOX_3_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SOFT_RESET_REG    ",             FPGA1_SOFT_RESET_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MISC_CTRL_REG     ",             FPGA1_MISC_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_MISC_STAT_REG     ",             FPGA1_MISC_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_FLSH_CTRL_REG     ",             FPGA1_FLSH_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_CTRL_REG     ",             FPGA1_ELBA0_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_STAT_REG     ",             FPGA1_ELBA0_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_WDOG_CTRL_REG",             FPGA1_ELBA0_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_WDOG_STAT_REG",             FPGA1_ELBA0_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_CTRL_REG     ",             FPGA1_ELBA1_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_STAT_REG     ",             FPGA1_ELBA1_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_WDOG_CTRL_REG",             FPGA1_ELBA1_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_WDOG_STAT_REG",             FPGA1_ELBA1_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_CTRL_REG     ",             FPGA1_ELBA2_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_STAT_REG     ",             FPGA1_ELBA2_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_WDOG_CTRL_REG",             FPGA1_ELBA2_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_WDOG_STAT_REG",             FPGA1_ELBA2_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_CTRL_REG     ",             FPGA1_ELBA3_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_STAT_REG     ",             FPGA1_ELBA3_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_WDOG_CTRL_REG",             FPGA1_ELBA3_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_WDOG_STAT_REG",             FPGA1_ELBA3_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_CTRL_REG     ",             FPGA1_ELBA4_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_STAT_REG     ",             FPGA1_ELBA4_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_WDOG_CTRL_REG",             FPGA1_ELBA4_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_WDOG_STAT_REG",             FPGA1_ELBA4_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_CTRL_REG     ",             FPGA1_ELBA5_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_STAT_REG     ",             FPGA1_ELBA5_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_WDOG_CTRL_REG",             FPGA1_ELBA5_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_WDOG_STAT_REG",             FPGA1_ELBA5_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_CTRL_REG     ",             FPGA1_ELBA6_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_STAT_REG     ",             FPGA1_ELBA6_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_WDOG_CTRL_REG",             FPGA1_ELBA6_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_WDOG_STAT_REG",             FPGA1_ELBA6_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_CTRL_REG     ",             FPGA1_ELBA7_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_STAT_REG     ",             FPGA1_ELBA7_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_WDOG_CTRL_REG",             FPGA1_ELBA7_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_WDOG_STAT_REG",             FPGA1_ELBA7_WDOG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_RXDATA_REG    ",             FPGA1_SPI0_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_TXDATA4B_REG  ",             FPGA1_SPI0_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_TXDATA2B_REG  ",             FPGA1_SPI0_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_TXDATA1B_REG  ",             FPGA1_SPI0_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_STATUS_REG    ",             FPGA1_SPI0_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_CONTROL_REG   ",             FPGA1_SPI0_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_SEM_REG       ",             FPGA1_SPI0_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_SLAVESEL_REG  ",             FPGA1_SPI0_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_EOP_VALUE_REG ",             FPGA1_SPI0_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI0_MUXSEL_REG    ",             FPGA1_SPI0_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_RXDATA_REG    ",             FPGA1_SPI1_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_TXDATA4B_REG  ",             FPGA1_SPI1_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_TXDATA2B_REG  ",             FPGA1_SPI1_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_TXDATA1B_REG  ",             FPGA1_SPI1_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_STATUS_REG    ",             FPGA1_SPI1_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_CONTROL_REG   ",             FPGA1_SPI1_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_SEM_REG       ",             FPGA1_SPI1_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_SLAVESEL_REG  ",             FPGA1_SPI1_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_EOP_VALUE_REG ",             FPGA1_SPI1_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI1_MUXSEL_REG    ",             FPGA1_SPI1_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_RXDATA_REG    ",             FPGA1_SPI2_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_TXDATA4B_REG  ",             FPGA1_SPI2_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_TXDATA2B_REG  ",             FPGA1_SPI2_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_TXDATA1B_REG  ",             FPGA1_SPI2_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_STATUS_REG    ",             FPGA1_SPI2_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_CONTROL_REG   ",             FPGA1_SPI2_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_SEM_REG       ",             FPGA1_SPI2_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_SLAVESEL_REG  ",             FPGA1_SPI2_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_EOP_VALUE_REG ",             FPGA1_SPI2_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI2_MUXSEL_REG    ",             FPGA1_SPI2_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_RXDATA_REG    ",             FPGA1_SPI3_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_TXDATA4B_REG  ",             FPGA1_SPI3_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_TXDATA2B_REG  ",             FPGA1_SPI3_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_TXDATA1B_REG  ",             FPGA1_SPI3_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_STATUS_REG    ",             FPGA1_SPI3_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_CONTROL_REG   ",             FPGA1_SPI3_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_SEM_REG       ",             FPGA1_SPI3_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_SLAVESEL_REG  ",             FPGA1_SPI3_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_EOP_VALUE_REG ",             FPGA1_SPI3_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI3_MUXSEL_REG    ",             FPGA1_SPI3_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_RXDATA_REG    ",             FPGA1_SPI4_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_TXDATA4B_REG  ",             FPGA1_SPI4_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_TXDATA2B_REG  ",             FPGA1_SPI4_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_TXDATA1B_REG  ",             FPGA1_SPI4_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_STATUS_REG    ",             FPGA1_SPI4_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_CONTROL_REG   ",             FPGA1_SPI4_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_SEM_REG       ",             FPGA1_SPI4_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_SLAVESEL_REG  ",             FPGA1_SPI4_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_EOP_VALUE_REG ",             FPGA1_SPI4_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI4_MUXSEL_REG    ",             FPGA1_SPI4_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_RXDATA_REG    ",             FPGA1_SPI5_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_TXDATA4B_REG  ",             FPGA1_SPI5_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_TXDATA2B_REG  ",             FPGA1_SPI5_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_TXDATA1B_REG  ",             FPGA1_SPI5_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_STATUS_REG    ",             FPGA1_SPI5_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_CONTROL_REG   ",             FPGA1_SPI5_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_SEM_REG       ",             FPGA1_SPI5_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_SLAVESEL_REG  ",             FPGA1_SPI5_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_EOP_VALUE_REG ",             FPGA1_SPI5_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI5_MUXSEL_REG    ",             FPGA1_SPI5_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_RXDATA_REG    ",             FPGA1_SPI6_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_TXDATA4B_REG  ",             FPGA1_SPI6_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_TXDATA2B_REG  ",             FPGA1_SPI6_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_TXDATA1B_REG  ",             FPGA1_SPI6_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_STATUS_REG    ",             FPGA1_SPI6_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_CONTROL_REG   ",             FPGA1_SPI6_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_SEM_REG       ",             FPGA1_SPI6_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_SLAVESEL_REG  ",             FPGA1_SPI6_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_EOP_VALUE_REG ",             FPGA1_SPI6_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI6_MUXSEL_REG    ",             FPGA1_SPI6_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_RXDATA_REG    ",             FPGA1_SPI7_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_TXDATA4B_REG  ",             FPGA1_SPI7_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_TXDATA2B_REG  ",             FPGA1_SPI7_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_TXDATA1B_REG  ",             FPGA1_SPI7_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_STATUS_REG    ",             FPGA1_SPI7_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_CONTROL_REG   ",             FPGA1_SPI7_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_SEM_REG       ",             FPGA1_SPI7_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_SLAVESEL_REG  ",             FPGA1_SPI7_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_EOP_VALUE_REG ",             FPGA1_SPI7_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI7_MUXSEL_REG    ",             FPGA1_SPI7_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_RXDATA_REG    ",             FPGA1_SPI8_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_TXDATA4B_REG  ",             FPGA1_SPI8_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_TXDATA2B_REG  ",             FPGA1_SPI8_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_TXDATA1B_REG  ",             FPGA1_SPI8_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_STATUS_REG    ",             FPGA1_SPI8_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_CONTROL_REG   ",             FPGA1_SPI8_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_SEM_REG       ",             FPGA1_SPI8_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_SLAVESEL_REG  ",             FPGA1_SPI8_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_EOP_VALUE_REG ",             FPGA1_SPI8_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI8_MUXSEL_REG    ",             FPGA1_SPI8_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_RXDATA_REG    ",             FPGA1_SPI9_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_TXDATA4B_REG  ",             FPGA1_SPI9_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_TXDATA2B_REG  ",             FPGA1_SPI9_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_TXDATA1B_REG  ",             FPGA1_SPI9_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_STATUS_REG    ",             FPGA1_SPI9_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_CONTROL_REG   ",             FPGA1_SPI9_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_SEM_REG       ",             FPGA1_SPI9_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_SLAVESEL_REG  ",             FPGA1_SPI9_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_EOP_VALUE_REG ",             FPGA1_SPI9_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI9_MUXSEL_REG    ",             FPGA1_SPI9_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_RXDATA_REG    ",             FPGA1_SPI10_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_TXDATA4B_REG  ",             FPGA1_SPI10_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_TXDATA2B_REG  ",             FPGA1_SPI10_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_TXDATA1B_REG  ",             FPGA1_SPI10_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_STATUS_REG    ",             FPGA1_SPI10_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_CONTROL_REG   ",             FPGA1_SPI10_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_SEM_REG       ",             FPGA1_SPI10_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_SLAVESEL_REG  ",             FPGA1_SPI10_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_EOP_VALUE_REG ",             FPGA1_SPI10_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI10_MUXSEL_REG    ",             FPGA1_SPI10_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_RXDATA_REG    ",             FPGA1_SPI11_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_TXDATA4B_REG  ",             FPGA1_SPI11_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_TXDATA2B_REG  ",             FPGA1_SPI11_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_TXDATA1B_REG  ",             FPGA1_SPI11_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_STATUS_REG    ",             FPGA1_SPI11_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_CONTROL_REG   ",             FPGA1_SPI11_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_SEM_REG       ",             FPGA1_SPI11_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_SLAVESEL_REG  ",             FPGA1_SPI11_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_EOP_VALUE_REG ",             FPGA1_SPI11_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI11_MUXSEL_REG    ",             FPGA1_SPI11_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_RXDATA_REG    ",             FPGA1_SPI12_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_TXDATA4B_REG  ",             FPGA1_SPI12_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_TXDATA2B_REG  ",             FPGA1_SPI12_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_TXDATA1B_REG  ",             FPGA1_SPI12_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_STATUS_REG    ",             FPGA1_SPI12_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_CONTROL_REG   ",             FPGA1_SPI12_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_SEM_REG       ",             FPGA1_SPI12_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_SLAVESEL_REG  ",             FPGA1_SPI12_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_EOP_VALUE_REG ",             FPGA1_SPI12_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI12_MUXSEL_REG    ",             FPGA1_SPI12_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_RXDATA_REG    ",             FPGA1_SPI13_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_TXDATA4B_REG  ",             FPGA1_SPI13_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_TXDATA2B_REG  ",             FPGA1_SPI13_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_TXDATA1B_REG  ",             FPGA1_SPI13_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_STATUS_REG    ",             FPGA1_SPI13_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_CONTROL_REG   ",             FPGA1_SPI13_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_SEM_REG       ",             FPGA1_SPI13_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_SLAVESEL_REG  ",             FPGA1_SPI13_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_EOP_VALUE_REG ",             FPGA1_SPI13_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI13_MUXSEL_REG    ",             FPGA1_SPI13_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_RXDATA_REG    ",             FPGA1_SPI14_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_TXDATA4B_REG  ",             FPGA1_SPI14_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_TXDATA2B_REG  ",             FPGA1_SPI14_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_TXDATA1B_REG  ",             FPGA1_SPI14_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_STATUS_REG    ",             FPGA1_SPI14_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_CONTROL_REG   ",             FPGA1_SPI14_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_SEM_REG       ",             FPGA1_SPI14_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_SLAVESEL_REG  ",             FPGA1_SPI14_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_EOP_VALUE_REG ",             FPGA1_SPI14_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI14_MUXSEL_REG    ",             FPGA1_SPI14_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_RXDATA_REG    ",             FPGA1_SPI15_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_TXDATA4B_REG  ",             FPGA1_SPI15_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_TXDATA2B_REG  ",             FPGA1_SPI15_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_TXDATA1B_REG  ",             FPGA1_SPI15_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_STATUS_REG    ",             FPGA1_SPI15_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_CONTROL_REG   ",             FPGA1_SPI15_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_SEM_REG       ",             FPGA1_SPI15_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_SLAVESEL_REG  ",             FPGA1_SPI15_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_EOP_VALUE_REG ",             FPGA1_SPI15_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI15_MUXSEL_REG    ",             FPGA1_SPI15_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_RXDATA_REG    ",             FPGA1_SPI16_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_TXDATA4B_REG  ",             FPGA1_SPI16_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_TXDATA2B_REG  ",             FPGA1_SPI16_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_TXDATA1B_REG  ",             FPGA1_SPI16_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_STATUS_REG    ",             FPGA1_SPI16_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_CONTROL_REG   ",             FPGA1_SPI16_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_SEM_REG       ",             FPGA1_SPI16_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_SLAVESEL_REG  ",             FPGA1_SPI16_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_EOP_VALUE_REG ",             FPGA1_SPI16_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_SPI16_MUXSEL_REG    ",             FPGA1_SPI16_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_PRSCL_LO_REG",             FPGA1_I2C_CH0_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_PRSCL_HI_REG",             FPGA1_I2C_CH0_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_CTRL_REG    ",             FPGA1_I2C_CH0_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_TX_REG      ",             FPGA1_I2C_CH0_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_RX_REG      ",             FPGA1_I2C_CH0_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_CMD_REG     ",             FPGA1_I2C_CH0_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_STAT_REG    ",             FPGA1_I2C_CH0_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_MUX_SEL_REG ",             FPGA1_I2C_CH0_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_RST_REG     ",             FPGA1_I2C_CH0_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH0_SEM_REG     ",             FPGA1_I2C_CH0_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_PRSCL_LO_REG",             FPGA1_I2C_CH1_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_PRSCL_HI_REG",             FPGA1_I2C_CH1_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_CTRL_REG    ",             FPGA1_I2C_CH1_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_TX_REG      ",             FPGA1_I2C_CH1_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_RX_REG      ",             FPGA1_I2C_CH1_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_CMD_REG     ",             FPGA1_I2C_CH1_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_STAT_REG    ",             FPGA1_I2C_CH1_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_MUX_SEL_REG ",             FPGA1_I2C_CH1_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_RST_REG     ",             FPGA1_I2C_CH1_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_I2C_CH1_SEM_REG     ",             FPGA1_I2C_CH1_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_CMD_REG       ",             FPGA1_ELBA0_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_STAT_REG      ",             FPGA1_ELBA0_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_ADDR0_REG     ",             FPGA1_ELBA0_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_ADDR1_REG     ",             FPGA1_ELBA0_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_TXDATA_REG    ",             FPGA1_ELBA0_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA0_J2C_RXDATA_REG    ",             FPGA1_ELBA0_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_CMD_REG       ",             FPGA1_ELBA1_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_STAT_REG      ",             FPGA1_ELBA1_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_ADDR0_REG     ",             FPGA1_ELBA1_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_ADDR1_REG     ",             FPGA1_ELBA1_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_TXDATA_REG    ",             FPGA1_ELBA1_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA1_J2C_RXDATA_REG    ",             FPGA1_ELBA1_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_CMD_REG       ",             FPGA1_ELBA2_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_STAT_REG      ",             FPGA1_ELBA2_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_ADDR0_REG     ",             FPGA1_ELBA2_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_ADDR1_REG     ",             FPGA1_ELBA2_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_TXDATA_REG    ",             FPGA1_ELBA2_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA2_J2C_RXDATA_REG    ",             FPGA1_ELBA2_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_CMD_REG       ",             FPGA1_ELBA3_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_STAT_REG      ",             FPGA1_ELBA3_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_ADDR0_REG     ",             FPGA1_ELBA3_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_ADDR1_REG     ",             FPGA1_ELBA3_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_TXDATA_REG    ",             FPGA1_ELBA3_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA3_J2C_RXDATA_REG    ",             FPGA1_ELBA3_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_CMD_REG       ",             FPGA1_ELBA4_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_STAT_REG      ",             FPGA1_ELBA4_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_ADDR0_REG     ",             FPGA1_ELBA4_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_ADDR1_REG     ",             FPGA1_ELBA4_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_TXDATA_REG    ",             FPGA1_ELBA4_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA4_J2C_RXDATA_REG    ",             FPGA1_ELBA4_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_CMD_REG       ",             FPGA1_ELBA5_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_STAT_REG      ",             FPGA1_ELBA5_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_ADDR0_REG     ",             FPGA1_ELBA5_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_ADDR1_REG     ",             FPGA1_ELBA5_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_TXDATA_REG    ",             FPGA1_ELBA5_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA5_J2C_RXDATA_REG    ",             FPGA1_ELBA5_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_CMD_REG       ",             FPGA1_ELBA6_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_STAT_REG      ",             FPGA1_ELBA6_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_ADDR0_REG     ",             FPGA1_ELBA6_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_ADDR1_REG     ",             FPGA1_ELBA6_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_TXDATA_REG    ",             FPGA1_ELBA6_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA6_J2C_RXDATA_REG    ",             FPGA1_ELBA6_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_CMD_REG       ",             FPGA1_ELBA7_J2C_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_STAT_REG      ",             FPGA1_ELBA7_J2C_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_ADDR0_REG     ",             FPGA1_ELBA7_J2C_ADDR0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_ADDR1_REG     ",             FPGA1_ELBA7_J2C_ADDR1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_TXDATA_REG    ",             FPGA1_ELBA7_J2C_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_ELBA7_J2C_RXDATA_REG    ",             FPGA1_ELBA7_J2C_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_CLOCK_REG     ",             FPGA1_RTC_CLOCK_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_TIMER_REG     ",             FPGA1_RTC_TIMER_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_STPWTCH_REG   ",             FPGA1_RTC_STPWTCH_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_ALARM_REG     ",             FPGA1_RTC_ALARM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_CKSPEED_REG   ",             FPGA1_RTC_CKSPEED_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_HACKTIME_REG  ",             FPGA1_RTC_HACKTIME_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_HACKCNTHI_REG ",             FPGA1_RTC_HACKCNTHI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_HACKCNTLO_REG ",             FPGA1_RTC_HACKCNTLO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA1_RTC_DATE_REG      ",             FPGA1_RTC_DATE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA0_UART_RXDATA_REG   ",             FPGA_ELBA0_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA0_UART_TXDATA_REG   ",             FPGA_ELBA0_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA0_UART_STAT_REG     ",             FPGA_ELBA0_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA0_UART_CTRL_REG     ",             FPGA_ELBA0_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA1_UART_RXDATA_REG   ",             FPGA_ELBA1_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA1_UART_TXDATA_REG   ",             FPGA_ELBA1_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA1_UART_STAT_REG     ",             FPGA_ELBA1_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA1_UART_CTRL_REG     ",             FPGA_ELBA1_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA2_UART_RXDATA_REG   ",             FPGA_ELBA2_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA2_UART_TXDATA_REG   ",             FPGA_ELBA2_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA2_UART_STAT_REG     ",             FPGA_ELBA2_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA2_UART_CTRL_REG     ",             FPGA_ELBA2_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA3_UART_RXDATA_REG   ",             FPGA_ELBA3_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA3_UART_TXDATA_REG   ",             FPGA_ELBA3_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA3_UART_STAT_REG     ",             FPGA_ELBA3_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA3_UART_CTRL_REG     ",             FPGA_ELBA3_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA4_UART_RXDATA_REG   ",             FPGA_ELBA4_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA4_UART_TXDATA_REG   ",             FPGA_ELBA4_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA4_UART_STAT_REG     ",             FPGA_ELBA4_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA4_UART_CTRL_REG     ",             FPGA_ELBA4_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA5_UART_RXDATA_REG   ",             FPGA_ELBA5_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA5_UART_TXDATA_REG   ",             FPGA_ELBA5_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA5_UART_STAT_REG     ",             FPGA_ELBA5_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA5_UART_CTRL_REG     ",             FPGA_ELBA5_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA6_UART_RXDATA_REG   ",             FPGA_ELBA6_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA6_UART_TXDATA_REG   ",             FPGA_ELBA6_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA6_UART_STAT_REG     ",             FPGA_ELBA6_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA6_UART_CTRL_REG     ",             FPGA_ELBA6_UART_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA7_UART_RXDATA_REG   ",             FPGA_ELBA7_UART_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA7_UART_TXDATA_REG   ",             FPGA_ELBA7_UART_TXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA7_UART_STAT_REG     ",             FPGA_ELBA7_UART_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA_ELBA7_UART_CTRL_REG     ",             FPGA_ELBA7_UART_CTRL_REG},
}

