package liparifpga


/*
 * Registers offset
 */


type LIPARI_FPGA_REGISTERS struct {
    Name     string
    Address  uint64
}

const L_I2C_MAILBOX_STRIDE = 0x20


const (
    FPGA0_DEVREGION = 0
    FPGA1_DEVREGION = 1
)

const FPGA0_FPGA_REV_ID_REG            uint64 = 0x0
const FPGA0_FPGA_DATECODE_REG          uint64 = 0x4
const FPGA0_FPGA_TIMECODE_REG          uint64 = 0x8
const FPGA0_BOARD_REV_ID_REG           uint64 = 0xC
const FPGA0_FUNC_CAP_0_REG             uint64 = 0x10
const FPGA0_FUNC_CAP_1_REG             uint64 = 0x14
const FPGA0_FUNC_CAP_2_REG             uint64 = 0x18
const FPGA0_FUNC_CAP_3_REG             uint64 = 0x1C
const FPGA0_FUNC_CAP_4_REG             uint64 = 0x20
const FPGA0_FUNC_CAP_5_REG             uint64 = 0x24
const FPGA0_FUNC_CAP_6_REG             uint64 = 0x28
const FPGA0_FUNC_CAP_7_REG             uint64 = 0x2C
const FPGA0_SCRATCH_0_REG              uint64 = 0x30
const FPGA0_SCRATCH_1_REG              uint64 = 0x34
const FPGA0_SCRATCH_2_REG              uint64 = 0x38
const FPGA0_SCRATCH_3_REG              uint64 = 0x3C
const FPGA0_LED_DEBUG_0_REG            uint64 = 0x40
const FPGA0_LED_DEBUG_1_REG            uint64 = 0x44
const FPGA0_LED_DEBUG_2_REG            uint64 = 0x48
const FPGA0_LED_DEBUG_3_REG            uint64 = 0x4C
const FPGA0_DEBUG_0_REG                uint64 = 0x50
const FPGA0_DEBUG_1_REG                uint64 = 0x54
const FPGA0_DEBUG_2_REG                uint64 = 0x58
const FPGA0_DEBUG_3_REG                uint64 = 0x5C
const FPGA0_INT0_EN_REG                uint64 = 0x60
const FPGA0_INT1_EN_REG                uint64 = 0x64
const FPGA0_INT2_EN_REG                uint64 = 0x68
const FPGA0_INT3_EN_REG                uint64 = 0x6C
const FPGA0_INT4_EN_REG                uint64 = 0x70
const FPGA0_INT5_EN_REG                uint64 = 0x74
const FPGA0_INT6_EN_REG                uint64 = 0x78
const FPGA0_INT7_EN_REG                uint64 = 0x7C
const FPGA0_INT0_PEND_REG              uint64 = 0x80
const FPGA0_INT1_PEND_REG              uint64 = 0x84
const FPGA0_INT2_PEND_REG              uint64 = 0x88
const FPGA0_INT3_PEND_REG              uint64 = 0x8C
const FPGA0_INT4_PEND_REG              uint64 = 0x90
const FPGA0_INT5_PEND_REG              uint64 = 0x94
const FPGA0_INT6_PEND_REG              uint64 = 0x98
const FPGA0_INT7_PEND_REG              uint64 = 0x9C
const FPGA0_BMC_INT0_EN_REG            uint64 = 0xA0
const FPGA0_BMC_INT1_EN_REG            uint64 = 0xA4
const FPGA0_BMC_INT2_EN_REG            uint64 = 0xA8
const FPGA0_BMC_INT3_EN_REG            uint64 = 0xAC
const FPGA0_BMC_INT4_EN_REG            uint64 = 0xB0
const FPGA0_BMC_INT5_EN_REG            uint64 = 0xB4
const FPGA0_BMC_INT6_EN_REG            uint64 = 0xB8
const FPGA0_BMC_INT7_EN_REG            uint64 = 0xBC
const FPGA0_BMC_INT0_PEND_REG          uint64 = 0xC0
const FPGA0_BMC_INT1_PEND_REG          uint64 = 0xC4
const FPGA0_BMC_INT2_PEND_REG          uint64 = 0xC8
const FPGA0_BMC_INT3_PEND_REG          uint64 = 0xCC
const FPGA0_BMC_INT4_PEND_REG          uint64 = 0xD0
const FPGA0_BMC_INT5_PEND_REG          uint64 = 0xD4
const FPGA0_BMC_INT6_PEND_REG          uint64 = 0xD8
const FPGA0_BMC_INT7_PEND_REG          uint64 = 0xDC
const FPGA0_RESET_CAUSE_0_REG          uint64 = 0x100
const FPGA0_RESET_CAUSE_1_REG          uint64 = 0x104
const FPGA0_RESET_CAUSE_2_REG          uint64 = 0x108
const FPGA0_RESET_CAUSE_3_REG          uint64 = 0x10C
const FPGA0_RESET_CAUSE_4_REG          uint64 = 0x110
const FPGA0_RESET_CAUSE_5_REG          uint64 = 0x114
const FPGA0_RESET_CAUSE_6_REG          uint64 = 0x118
const FPGA0_RESET_CAUSE_7_REG          uint64 = 0x11C
const FPGA0_FPGA_RECONFIG_CTRL_REG     uint64 = 0x120
const FPGA0_FPGA_RECONFIG_STAT_REG     uint64 = 0x124
const FPGA0_MBOX_STAT_REG              uint64 = 0x180
const FPGA0_MBOX_STAT_PLRTY_REG        uint64 = 0x184
const FPGA0_MBOX_STAT_EDG_LVL_REG      uint64 = 0x188
const FPGA0_MBOX_STAT_INT_EN_REG       uint64 = 0x18C
const FPGA0_MBOX_STAT_INT_STAT_REG     uint64 = 0x190
const FPGA0_MBOX_STAT_INT_CLR_REG      uint64 = 0x194
const FPGA0_MBOX_0_DATA_REG            uint64 = 0x198
const FPGA0_MBOX_1_DATA_REG            uint64 = 0x19C
const FPGA0_MBOX_2_DATA_REG            uint64 = 0x1A0
const FPGA0_MBOX_3_DATA_REG            uint64 = 0x1A4
const FPGA0_SOFT_RESET_REG             uint64 = 0x1A8
const FPGA0_FLSH_CTRL_REG              uint64 = 0x1AC
const FPGA0_LED_CONFIG_REG             uint64 = 0x1B0
const FPGA0_LED_SYSTEM_REG             uint64 = 0x1B4
const FPGA0_LED_FAN_REG                uint64 = 0x1B8
const FPGA0_LED_FP0300_REG             uint64 = 0x220
const FPGA0_LED_FP0704_REG             uint64 = 0x224
const FPGA0_LED_FP1108_REG             uint64 = 0x228
const FPGA0_LED_FP1512_REG             uint64 = 0x22C
const FPGA0_LED_FP1916_REG             uint64 = 0x230
const FPGA0_LED_FP2320_REG             uint64 = 0x234
const FPGA0_LED_FP2724_REG             uint64 = 0x238
const FPGA0_QDD_0300_STAT_REG          uint64 = 0x300
const FPGA0_QDD_0300_CTRL_REG          uint64 = 0x304
const FPGA0_QDD_0704_STAT_REG          uint64 = 0x308
const FPGA0_QDD_0704_CTRL_REG          uint64 = 0x30C
const FPGA0_QDD_1108_STAT_REG          uint64 = 0x310
const FPGA0_QDD_1108_CTRL_REG          uint64 = 0x314
const FPGA0_QDD_1512_STAT_REG          uint64 = 0x318
const FPGA0_QDD_1512_CTRL_REG          uint64 = 0x31C
const FPGA0_QDD_1916_STAT_REG          uint64 = 0x320
const FPGA0_QDD_1916_CTRL_REG          uint64 = 0x324
const FPGA0_QDD_2320_STAT_REG          uint64 = 0x328
const FPGA0_QDD_2320_CTRL_REG          uint64 = 0x32C
const FPGA0_QDD_2724_STAT_REG          uint64 = 0x330
const FPGA0_QDD_2724_CTRL_REG          uint64 = 0x334
const FPGA0_SPI0_RXDATA_REG            uint64 = 0x400   //fpga flash
const FPGA0_SPI0_TXDATA4B_REG          uint64 = 0x404
const FPGA0_SPI0_TXDATA2B_REG          uint64 = 0x408
const FPGA0_SPI0_TXDATA1B_REG          uint64 = 0x40C
const FPGA0_SPI0_STATUS_REG            uint64 = 0x410
const FPGA0_SPI0_CONTROL_REG           uint64 = 0x414
const FPGA0_SPI0_SEM_REG               uint64 = 0x418
const FPGA0_SPI0_SLAVESEL_REG          uint64 = 0x41C
const FPGA0_SPI0_EOP_VALUE_REG         uint64 = 0x420
const FPGA0_SPI0_MUXSEL_REG            uint64 = 0x424
const FPGA0_PSU_CTRL_REG               uint64 = 0x500
const FPGA0_PSU_STAT_REG               uint64 = 0x504
    const FPGA0_PSU_STAT_REG_PRESENT0    uint32 = (1<<0)
    const FPGA0_PSU_STAT_PWROK0          uint32 = (1<<2)
    const FPGA0_PSU_STAT_INT0            uint32 = (1<<3)
    const FPGA0_PSU_STAT_REG_PRESENT1    uint32 = (1<<8)
    const FPGA0_PSU_STAT_PWROK1          uint32 = (1<<10)
    const FPGA0_PSU_STAT_INT1            uint32 = (1<<11)
const FPGA0_FAN_CTRL_REG               uint64 = 0x508
const FPGA0_FAN_PWM_CTRL_REG           uint64 = 0x50C
const FPGA0_FAN_STAT_REG               uint64 = 0x510
    //FAN PRESENCE IS INVERTED.  0 = PRESENT,  1 = NOT PRESENT
    const FPGA0_FAN_STAT_REG_NOT_PRESENT0_BIT   uint32 = 0x01
    const FPGA0_FAN_STAT_REG_NOT_PRESENT0_SHIFT uint32 = 0x00
    const FPGA0_FAN_STAT_REG_NOT_PRESENT0       uint32 = (FPGA0_FAN_STAT_REG_NOT_PRESENT0_BIT<<FPGA0_FAN_STAT_REG_NOT_PRESENT0_SHIFT)
    const FPGA0_FAN_STAT_PORT_SIDE_INTAKE_MASK  uint32 = 0x0F00
    const FPGA0_FAN_STAT_PORT_SIDE_SHIFT        uint32 = 8
const FPGA0_FAN0_TACH_REG              uint64 = 0x514
const FPGA0_FAN1_TACH_REG              uint64 = 0x518
const FPGA0_FAN2_TACH_REG              uint64 = 0x51C
const FPGA0_FAN3_TACH_REG              uint64 = 0x520
const FPGA0_ELBA0_PWR_CTRL_REG         uint64 = 0x540
const FPGA0_ELBA0_PWR_STAT_REG         uint64 = 0x544
const FPGA0_ELBA1_PWR_CTRL_REG         uint64 = 0x548
const FPGA0_ELBA1_PWR_STAT_REG         uint64 = 0x54C
const FPGA0_ELBA2_PWR_CTRL_REG         uint64 = 0x550
const FPGA0_ELBA2_PWR_STAT_REG         uint64 = 0x554
const FPGA0_ELBA3_PWR_CTRL_REG         uint64 = 0x558
const FPGA0_ELBA3_PWR_STAT_REG         uint64 = 0x55C
const FPGA0_ELBA4_PWR_CTRL_REG         uint64 = 0x560
const FPGA0_ELBA4_PWR_STAT_REG         uint64 = 0x564
const FPGA0_ELBA5_PWR_CTRL_REG         uint64 = 0x568
const FPGA0_ELBA5_PWR_STAT_REG         uint64 = 0x56C
const FPGA0_ELBA6_PWR_CTRL_REG         uint64 = 0x570
const FPGA0_ELBA6_PWR_STAT_REG         uint64 = 0x574
const FPGA0_ELBA7_PWR_CTRL_REG         uint64 = 0x578
const FPGA0_ELBA7_PWR_STAT_REG         uint64 = 0x57C
const FPGA0_TH4_PWR_CTRL_REG           uint64 = 0x580
const FPGA0_TH4_PWR_STAT_REG           uint64 = 0x584
const FPGA0_TH4_CTRL_REG               uint64 = 0x588
const FPGA0_TH4_STAT_REG               uint64 = 0x58C
const FPGA0_MISC_PWR_CTRL_REG          uint64 = 0x590
const FPGA0_MISC_PWR_STAT_REG          uint64 = 0x594
const FPGA0_MISC_CTRL_REG              uint64 = 0x598
const FPGA0_MISC_STAT_REG              uint64 = 0x59C
const FPGA0_CPU_CTRL_REG               uint64 = 0x5A0
const FPGA0_CPU_STAT_REG               uint64 = 0x5A4
const FPGA0_WDOG_CTRL_REG              uint64 = 0x5A8
const FPGA0_WDOG_RESET_REG             uint64 = 0x5AC
const FPGA0_SPI1_RXDATA_REG            uint64 = 0x600   //cpu CPLD on CPU BOARD
const FPGA0_SPI1_TXDATA4B_REG          uint64 = 0x604
const FPGA0_SPI1_TXDATA2B_REG          uint64 = 0x608
const FPGA0_SPI1_TXDATA1B_REG          uint64 = 0x60C
const FPGA0_SPI1_STATUS_REG            uint64 = 0x610
const FPGA0_SPI1_CONTROL_REG           uint64 = 0x614
const FPGA0_SPI1_SEM_REG               uint64 = 0x618
const FPGA0_SPI1_SLAVESEL_REG          uint64 = 0x61C
const FPGA0_SPI1_EOP_VALUE_REG         uint64 = 0x620
const FPGA0_SPI1_MUXSEL_REG            uint64 = 0x624
const FPGA0_I2C_CH0_PRSCL_LO_REG       uint64 = 0x700
const FPGA0_I2C_CH0_PRSCL_HI_REG       uint64 = 0x704
const FPGA0_I2C_CH0_CTRL_REG           uint64 = 0x708
const FPGA0_I2C_CH0_TX_REG             uint64 = 0x70C
const FPGA0_I2C_CH0_RX_REG             uint64 = 0x70C
const FPGA0_I2C_CH0_CMD_REG            uint64 = 0x710
const FPGA0_I2C_CH0_STAT_REG           uint64 = 0x710
const FPGA0_I2C_CH0_MUX_SEL_REG        uint64 = 0x714
const FPGA0_I2C_CH0_RST_REG            uint64 = 0x718
const FPGA0_I2C_CH0_SEM_REG            uint64 = 0x71C
const FPGA0_I2C_CH1_PRSCL_LO_REG       uint64 = 0x720
const FPGA0_I2C_CH1_PRSCL_HI_REG       uint64 = 0x724
const FPGA0_I2C_CH1_CTRL_REG           uint64 = 0x728
const FPGA0_I2C_CH1_TX_REG             uint64 = 0x72C
const FPGA0_I2C_CH1_RX_REG             uint64 = 0x72C
const FPGA0_I2C_CH1_CMD_REG            uint64 = 0x730
const FPGA0_I2C_CH1_STAT_REG           uint64 = 0x730
const FPGA0_I2C_CH1_MUX_SEL_REG        uint64 = 0x734
const FPGA0_I2C_CH1_RST_REG            uint64 = 0x738
const FPGA0_I2C_CH1_SEM_REG            uint64 = 0x73C
const FPGA0_I2C_CH2_PRSCL_LO_REG       uint64 = 0x740
const FPGA0_I2C_CH2_PRSCL_HI_REG       uint64 = 0x744
const FPGA0_I2C_CH2_CTRL_REG           uint64 = 0x748
const FPGA0_I2C_CH2_TX_REG             uint64 = 0x74C
const FPGA0_I2C_CH2_RX_REG             uint64 = 0x74C
const FPGA0_I2C_CH2_CMD_REG            uint64 = 0x750
const FPGA0_I2C_CH2_STAT_REG           uint64 = 0x750
const FPGA0_I2C_CH2_MUX_SEL_REG        uint64 = 0x754
const FPGA0_I2C_CH2_RST_REG            uint64 = 0x758
const FPGA0_I2C_CH2_SEM_REG            uint64 = 0x75C
const FPGA0_I2C_CH3_PRSCL_LO_REG       uint64 = 0x760
const FPGA0_I2C_CH3_PRSCL_HI_REG       uint64 = 0x764
const FPGA0_I2C_CH3_CTRL_REG           uint64 = 0x768
const FPGA0_I2C_CH3_TX_REG             uint64 = 0x76C
const FPGA0_I2C_CH3_RX_REG             uint64 = 0x76C
const FPGA0_I2C_CH3_CMD_REG            uint64 = 0x770
const FPGA0_I2C_CH3_STAT_REG           uint64 = 0x770
const FPGA0_I2C_CH3_MUX_SEL_REG        uint64 = 0x774
const FPGA0_I2C_CH3_RST_REG            uint64 = 0x778
const FPGA0_I2C_CH3_SEM_REG            uint64 = 0x77C
const FPGA0_I2C_CH4_PRSCL_LO_REG       uint64 = 0x780
const FPGA0_I2C_CH4_PRSCL_HI_REG       uint64 = 0x784
const FPGA0_I2C_CH4_CTRL_REG           uint64 = 0x788
const FPGA0_I2C_CH4_TX_REG             uint64 = 0x78C
const FPGA0_I2C_CH4_RX_REG             uint64 = 0x78C
const FPGA0_I2C_CH4_CMD_REG            uint64 = 0x790
const FPGA0_I2C_CH4_STAT_REG           uint64 = 0x790
const FPGA0_I2C_CH4_MUX_SEL_REG        uint64 = 0x794
const FPGA0_I2C_CH4_RST_REG            uint64 = 0x798
const FPGA0_I2C_CH4_SEM_REG            uint64 = 0x79C
const FPGA0_I2C_CH5_PRSCL_LO_REG       uint64 = 0x7A0
const FPGA0_I2C_CH5_PRSCL_HI_REG       uint64 = 0x7A4
const FPGA0_I2C_CH5_CTRL_REG           uint64 = 0x7A8
const FPGA0_I2C_CH5_TX_REG             uint64 = 0x7AC
const FPGA0_I2C_CH5_RX_REG             uint64 = 0x7AC
const FPGA0_I2C_CH5_CMD_REG            uint64 = 0x7B0
const FPGA0_I2C_CH5_STAT_REG           uint64 = 0x7B0
const FPGA0_I2C_CH5_MUX_SEL_REG        uint64 = 0x7B4
const FPGA0_I2C_CH5_RST_REG            uint64 = 0x7B8
const FPGA0_I2C_CH5_SEM_REG            uint64 = 0x7BC
const FPGA0_I2C_CH6_PRSCL_LO_REG       uint64 = 0x7C0
const FPGA0_I2C_CH6_PRSCL_HI_REG       uint64 = 0x7C4
const FPGA0_I2C_CH6_CTRL_REG           uint64 = 0x7C8
const FPGA0_I2C_CH6_TX_REG             uint64 = 0x7CC
const FPGA0_I2C_CH6_RX_REG             uint64 = 0x7CC
const FPGA0_I2C_CH6_CMD_REG            uint64 = 0x7D0
const FPGA0_I2C_CH6_STAT_REG           uint64 = 0x7D0
const FPGA0_I2C_CH6_MUX_SEL_REG        uint64 = 0x7D4
const FPGA0_I2C_CH6_RST_REG            uint64 = 0x7D8
const FPGA0_I2C_CH6_SEM_REG            uint64 = 0x7DC
const FPGA0_I2C_CH7_PRSCL_LO_REG       uint64 = 0x7E0
const FPGA0_I2C_CH7_PRSCL_HI_REG       uint64 = 0x7E4
const FPGA0_I2C_CH7_CTRL_REG           uint64 = 0x7E8
const FPGA0_I2C_CH7_TX_REG             uint64 = 0x7EC
const FPGA0_I2C_CH7_RX_REG             uint64 = 0x7EC
const FPGA0_I2C_CH7_CMD_REG            uint64 = 0x7F0
const FPGA0_I2C_CH7_STAT_REG           uint64 = 0x7F0
const FPGA0_I2C_CH7_MUX_SEL_REG        uint64 = 0x7F4
const FPGA0_I2C_CH7_RST_REG            uint64 = 0x7F8
const FPGA0_I2C_CH7_SEM_REG            uint64 = 0x7FC
const FPGA0_I2C_CH8_PRSCL_LO_REG       uint64 = 0x800
const FPGA0_I2C_CH8_PRSCL_HI_REG       uint64 = 0x804
const FPGA0_I2C_CH8_CTRL_REG           uint64 = 0x808
const FPGA0_I2C_CH8_TX_REG             uint64 = 0x80C
const FPGA0_I2C_CH8_RX_REG             uint64 = 0x80C
const FPGA0_I2C_CH8_CMD_REG            uint64 = 0x810
const FPGA0_I2C_CH8_STAT_REG           uint64 = 0x810
const FPGA0_I2C_CH8_MUX_SEL_REG        uint64 = 0x814
const FPGA0_I2C_CH8_RST_REG            uint64 = 0x818
const FPGA0_I2C_CH8_SEM_REG            uint64 = 0x81C
const FPGA0_I2C_CH9_PRSCL_LO_REG       uint64 = 0x820
const FPGA0_I2C_CH9_PRSCL_HI_REG       uint64 = 0x824
const FPGA0_I2C_CH9_CTRL_REG           uint64 = 0x828
const FPGA0_I2C_CH9_TX_REG             uint64 = 0x82C
const FPGA0_I2C_CH9_RX_REG             uint64 = 0x82C
const FPGA0_I2C_CH9_CMD_REG            uint64 = 0x830
const FPGA0_I2C_CH9_STAT_REG           uint64 = 0x830
const FPGA0_I2C_CH9_MUX_SEL_REG        uint64 = 0x834
const FPGA0_I2C_CH9_RST_REG            uint64 = 0x838
const FPGA0_I2C_CH9_SEM_REG            uint64 = 0x83C


var LIPARI_FPGA0_REGISTERS = []LIPARI_FPGA_REGISTERS {
    LIPARI_FPGA_REGISTERS{"FPGA0_FPGA_REV_ID_REG      ",             FPGA0_FPGA_REV_ID_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FPGA_DATECODE_REG    ",             FPGA0_FPGA_DATECODE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FPGA_TIMECODE_REG    ",             FPGA0_FPGA_TIMECODE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BOARD_REV_ID_REG     ",             FPGA0_BOARD_REV_ID_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_0_REG       ",             FPGA0_FUNC_CAP_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_1_REG       ",             FPGA0_FUNC_CAP_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_2_REG       ",             FPGA0_FUNC_CAP_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_3_REG       ",             FPGA0_FUNC_CAP_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_4_REG       ",             FPGA0_FUNC_CAP_4_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_5_REG       ",             FPGA0_FUNC_CAP_5_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_6_REG       ",             FPGA0_FUNC_CAP_6_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FUNC_CAP_7_REG       ",             FPGA0_FUNC_CAP_7_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SCRATCH_0_REG        ",             FPGA0_SCRATCH_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SCRATCH_1_REG        ",             FPGA0_SCRATCH_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SCRATCH_2_REG        ",             FPGA0_SCRATCH_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SCRATCH_3_REG        ",             FPGA0_SCRATCH_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_DEBUG_0_REG      ",             FPGA0_LED_DEBUG_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_DEBUG_1_REG      ",             FPGA0_LED_DEBUG_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_DEBUG_2_REG      ",             FPGA0_LED_DEBUG_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_DEBUG_3_REG      ",             FPGA0_LED_DEBUG_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_DEBUG_0_REG          ",             FPGA0_DEBUG_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_DEBUG_1_REG          ",             FPGA0_DEBUG_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_DEBUG_2_REG          ",             FPGA0_DEBUG_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_DEBUG_3_REG          ",             FPGA0_DEBUG_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT0_EN_REG          ",             FPGA0_INT0_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT1_EN_REG          ",             FPGA0_INT1_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT2_EN_REG          ",             FPGA0_INT2_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT3_EN_REG          ",             FPGA0_INT3_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT4_EN_REG          ",             FPGA0_INT4_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT5_EN_REG          ",             FPGA0_INT5_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT6_EN_REG          ",             FPGA0_INT6_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT7_EN_REG          ",             FPGA0_INT7_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT0_PEND_REG        ",             FPGA0_INT0_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT1_PEND_REG        ",             FPGA0_INT1_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT2_PEND_REG        ",             FPGA0_INT2_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT3_PEND_REG        ",             FPGA0_INT3_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT4_PEND_REG        ",             FPGA0_INT4_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT5_PEND_REG        ",             FPGA0_INT5_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT6_PEND_REG        ",             FPGA0_INT6_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_INT7_PEND_REG        ",             FPGA0_INT7_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT0_EN_REG      ",             FPGA0_BMC_INT0_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT1_EN_REG      ",             FPGA0_BMC_INT1_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT2_EN_REG      ",             FPGA0_BMC_INT2_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT3_EN_REG      ",             FPGA0_BMC_INT3_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT4_EN_REG      ",             FPGA0_BMC_INT4_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT5_EN_REG      ",             FPGA0_BMC_INT5_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT6_EN_REG      ",             FPGA0_BMC_INT6_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT7_EN_REG      ",             FPGA0_BMC_INT7_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT0_PEND_REG    ",             FPGA0_BMC_INT0_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT1_PEND_REG    ",             FPGA0_BMC_INT1_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT2_PEND_REG    ",             FPGA0_BMC_INT2_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT3_PEND_REG    ",             FPGA0_BMC_INT3_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT4_PEND_REG    ",             FPGA0_BMC_INT4_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT5_PEND_REG    ",             FPGA0_BMC_INT5_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT6_PEND_REG    ",             FPGA0_BMC_INT6_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_BMC_INT7_PEND_REG    ",             FPGA0_BMC_INT7_PEND_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_0_REG    ",             FPGA0_RESET_CAUSE_0_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_1_REG    ",             FPGA0_RESET_CAUSE_1_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_2_REG    ",             FPGA0_RESET_CAUSE_2_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_3_REG    ",             FPGA0_RESET_CAUSE_3_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_4_REG    ",             FPGA0_RESET_CAUSE_4_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_5_REG    ",             FPGA0_RESET_CAUSE_5_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_6_REG    ",             FPGA0_RESET_CAUSE_6_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_RESET_CAUSE_7_REG    ",             FPGA0_RESET_CAUSE_7_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FPGA_RECONFIG_CTRL_REG",             FPGA0_FPGA_RECONFIG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FPGA_RECONFIG_STAT_REG",             FPGA0_FPGA_RECONFIG_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_REG        ",             FPGA0_MBOX_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_PLRTY_REG  ",             FPGA0_MBOX_STAT_PLRTY_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_EDG_LVL_REG",             FPGA0_MBOX_STAT_EDG_LVL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_INT_EN_REG ",             FPGA0_MBOX_STAT_INT_EN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_INT_STAT_REG",             FPGA0_MBOX_STAT_INT_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_STAT_INT_CLR_REG",             FPGA0_MBOX_STAT_INT_CLR_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_0_DATA_REG      ",             FPGA0_MBOX_0_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_1_DATA_REG      ",             FPGA0_MBOX_1_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_2_DATA_REG      ",             FPGA0_MBOX_2_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MBOX_3_DATA_REG      ",             FPGA0_MBOX_3_DATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SOFT_RESET_REG       ",             FPGA0_SOFT_RESET_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FLSH_CTRL_REG        ",             FPGA0_FLSH_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_CONFIG_REG       ",             FPGA0_LED_CONFIG_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_SYSTEM_REG       ",             FPGA0_LED_SYSTEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FAN_REG          ",             FPGA0_LED_FAN_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP0300_REG       ",             FPGA0_LED_FP0300_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP0704_REG       ",             FPGA0_LED_FP0704_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP1108_REG       ",             FPGA0_LED_FP1108_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP1512_REG       ",             FPGA0_LED_FP1512_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP1916_REG       ",             FPGA0_LED_FP1916_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP2320_REG       ",             FPGA0_LED_FP2320_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_LED_FP2724_REG       ",             FPGA0_LED_FP2724_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_0300_STAT_REG    ",             FPGA0_QDD_0300_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_0300_CTRL_REG    ",             FPGA0_QDD_0300_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_0704_STAT_REG    ",             FPGA0_QDD_0704_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_0704_CTRL_REG    ",             FPGA0_QDD_0704_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1108_STAT_REG    ",             FPGA0_QDD_1108_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1108_CTRL_REG    ",             FPGA0_QDD_1108_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1512_STAT_REG    ",             FPGA0_QDD_1512_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1512_CTRL_REG    ",             FPGA0_QDD_1512_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1916_STAT_REG    ",             FPGA0_QDD_1916_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_1916_CTRL_REG    ",             FPGA0_QDD_1916_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_2320_STAT_REG    ",             FPGA0_QDD_2320_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_2320_CTRL_REG    ",             FPGA0_QDD_2320_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_2724_STAT_REG    ",             FPGA0_QDD_2724_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_QDD_2724_CTRL_REG    ",             FPGA0_QDD_2724_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_RXDATA_REG      ",             FPGA0_SPI0_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_TXDATA4B_REG    ",             FPGA0_SPI0_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_TXDATA2B_REG    ",             FPGA0_SPI0_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_TXDATA1B_REG    ",             FPGA0_SPI0_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_STATUS_REG      ",             FPGA0_SPI0_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_CONTROL_REG     ",             FPGA0_SPI0_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_SEM_REG         ",             FPGA0_SPI0_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_SLAVESEL_REG    ",             FPGA0_SPI0_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_EOP_VALUE_REG   ",             FPGA0_SPI0_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI0_MUXSEL_REG      ",             FPGA0_SPI0_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_PSU_CTRL_REG         ",             FPGA0_PSU_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_PSU_STAT_REG         ",             FPGA0_PSU_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN_CTRL_REG         ",             FPGA0_FAN_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN_PWM_CTRL_REG     ",             FPGA0_FAN_PWM_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN_STAT_REG         ",             FPGA0_FAN_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN0_TACH_REG        ",             FPGA0_FAN0_TACH_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN1_TACH_REG        ",             FPGA0_FAN1_TACH_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN2_TACH_REG        ",             FPGA0_FAN2_TACH_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_FAN3_TACH_REG        ",             FPGA0_FAN3_TACH_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA0_PWR_CTRL_REG   ",             FPGA0_ELBA0_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA0_PWR_STAT_REG   ",             FPGA0_ELBA0_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA1_PWR_CTRL_REG   ",             FPGA0_ELBA1_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA1_PWR_STAT_REG   ",             FPGA0_ELBA1_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA2_PWR_CTRL_REG   ",             FPGA0_ELBA2_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA2_PWR_STAT_REG   ",             FPGA0_ELBA2_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA3_PWR_CTRL_REG   ",             FPGA0_ELBA3_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA3_PWR_STAT_REG   ",             FPGA0_ELBA3_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA4_PWR_CTRL_REG   ",             FPGA0_ELBA4_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA4_PWR_STAT_REG   ",             FPGA0_ELBA4_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA5_PWR_CTRL_REG   ",             FPGA0_ELBA5_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA5_PWR_STAT_REG   ",             FPGA0_ELBA5_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA6_PWR_CTRL_REG   ",             FPGA0_ELBA6_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA6_PWR_STAT_REG   ",             FPGA0_ELBA6_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA7_PWR_CTRL_REG   ",             FPGA0_ELBA7_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_ELBA7_PWR_STAT_REG   ",             FPGA0_ELBA7_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_TH4_PWR_CTRL_REG     ",             FPGA0_TH4_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_TH4_PWR_STAT_REG     ",             FPGA0_TH4_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_TH4_CTRL_REG         ",             FPGA0_TH4_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_TH4_STAT_REG         ",             FPGA0_TH4_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MISC_PWR_CTRL_REG    ",             FPGA0_MISC_PWR_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MISC_PWR_STAT_REG    ",             FPGA0_MISC_PWR_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MISC_CTRL_REG        ",             FPGA0_MISC_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_MISC_STAT_REG        ",             FPGA0_MISC_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_CPU_CTRL_REG         ",             FPGA0_CPU_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_CPU_STAT_REG         ",             FPGA0_CPU_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_WDOG_CTRL_REG        ",             FPGA0_WDOG_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_WDOG_RESET_REG       ",             FPGA0_WDOG_RESET_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI_RXDATA_REG       ",             FPGA0_SPI1_RXDATA_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_TXDATA4B_REG    ",             FPGA0_SPI1_TXDATA4B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_TXDATA2B_REG    ",             FPGA0_SPI1_TXDATA2B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_TXDATA1B_REG    ",             FPGA0_SPI1_TXDATA1B_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_STATUS_REG      ",             FPGA0_SPI1_STATUS_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_CONTROL_REG     ",             FPGA0_SPI1_CONTROL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_SEM_REG         ",             FPGA0_SPI1_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_SLAVESEL_REG    ",             FPGA0_SPI1_SLAVESEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_EOP_VALUE_REG   ",             FPGA0_SPI1_EOP_VALUE_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_SPI1_MUXSEL_REG      ",             FPGA0_SPI1_MUXSEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_PRSCL_LO_REG ",             FPGA0_I2C_CH0_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_PRSCL_HI_REG ",             FPGA0_I2C_CH0_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_CTRL_REG     ",             FPGA0_I2C_CH0_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_TX_REG       ",             FPGA0_I2C_CH0_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_RX_REG       ",             FPGA0_I2C_CH0_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_CMD_REG      ",             FPGA0_I2C_CH0_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_STAT_REG     ",             FPGA0_I2C_CH0_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_MUX_SEL_REG  ",             FPGA0_I2C_CH0_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_RST_REG      ",             FPGA0_I2C_CH0_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH0_SEM_REG      ",             FPGA0_I2C_CH0_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_PRSCL_LO_REG ",             FPGA0_I2C_CH1_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_PRSCL_HI_REG ",             FPGA0_I2C_CH1_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_CTRL_REG     ",             FPGA0_I2C_CH1_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_TX_REG       ",             FPGA0_I2C_CH1_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_RX_REG       ",             FPGA0_I2C_CH1_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_CMD_REG      ",             FPGA0_I2C_CH1_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_STAT_REG     ",             FPGA0_I2C_CH1_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_MUX_SEL_REG  ",             FPGA0_I2C_CH1_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_RST_REG      ",             FPGA0_I2C_CH1_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH1_SEM_REG      ",             FPGA0_I2C_CH1_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_PRSCL_LO_REG ",             FPGA0_I2C_CH2_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_PRSCL_HI_REG ",             FPGA0_I2C_CH2_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_CTRL_REG     ",             FPGA0_I2C_CH2_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_TX_REG       ",             FPGA0_I2C_CH2_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_RX_REG       ",             FPGA0_I2C_CH2_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_CMD_REG      ",             FPGA0_I2C_CH2_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_STAT_REG     ",             FPGA0_I2C_CH2_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_MUX_SEL_REG  ",             FPGA0_I2C_CH2_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_RST_REG      ",             FPGA0_I2C_CH2_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH2_SEM_REG      ",             FPGA0_I2C_CH2_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_PRSCL_LO_REG ",             FPGA0_I2C_CH3_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_PRSCL_HI_REG ",             FPGA0_I2C_CH3_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_CTRL_REG     ",             FPGA0_I2C_CH3_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_TX_REG       ",             FPGA0_I2C_CH3_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_RX_REG       ",             FPGA0_I2C_CH3_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_CMD_REG      ",             FPGA0_I2C_CH3_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_STAT_REG     ",             FPGA0_I2C_CH3_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_MUX_SEL_REG  ",             FPGA0_I2C_CH3_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_RST_REG      ",             FPGA0_I2C_CH3_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH3_SEM_REG      ",             FPGA0_I2C_CH3_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_PRSCL_LO_REG ",             FPGA0_I2C_CH4_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_PRSCL_HI_REG ",             FPGA0_I2C_CH4_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_CTRL_REG     ",             FPGA0_I2C_CH4_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_TX_REG       ",             FPGA0_I2C_CH4_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_RX_REG       ",             FPGA0_I2C_CH4_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_CMD_REG      ",             FPGA0_I2C_CH4_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_STAT_REG     ",             FPGA0_I2C_CH4_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_MUX_SEL_REG  ",             FPGA0_I2C_CH4_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_RST_REG      ",             FPGA0_I2C_CH4_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH4_SEM_REG      ",             FPGA0_I2C_CH4_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_PRSCL_LO_REG ",             FPGA0_I2C_CH5_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_PRSCL_HI_REG ",             FPGA0_I2C_CH5_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_CTRL_REG     ",             FPGA0_I2C_CH5_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_TX_REG       ",             FPGA0_I2C_CH5_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_RX_REG       ",             FPGA0_I2C_CH5_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_CMD_REG      ",             FPGA0_I2C_CH5_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_STAT_REG     ",             FPGA0_I2C_CH5_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_MUX_SEL_REG  ",             FPGA0_I2C_CH5_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_RST_REG      ",             FPGA0_I2C_CH5_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH5_SEM_REG      ",             FPGA0_I2C_CH5_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_PRSCL_LO_REG ",             FPGA0_I2C_CH6_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_PRSCL_HI_REG ",             FPGA0_I2C_CH6_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_CTRL_REG     ",             FPGA0_I2C_CH6_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_TX_REG       ",             FPGA0_I2C_CH6_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_RX_REG       ",             FPGA0_I2C_CH6_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_CMD_REG      ",             FPGA0_I2C_CH6_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_STAT_REG     ",             FPGA0_I2C_CH6_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_MUX_SEL_REG  ",             FPGA0_I2C_CH6_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_RST_REG      ",             FPGA0_I2C_CH6_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH6_SEM_REG      ",             FPGA0_I2C_CH6_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_PRSCL_LO_REG ",             FPGA0_I2C_CH7_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_PRSCL_HI_REG ",             FPGA0_I2C_CH7_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_CTRL_REG     ",             FPGA0_I2C_CH7_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_TX_REG       ",             FPGA0_I2C_CH7_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_RX_REG       ",             FPGA0_I2C_CH7_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_CMD_REG      ",             FPGA0_I2C_CH7_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_STAT_REG     ",             FPGA0_I2C_CH7_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_MUX_SEL_REG  ",             FPGA0_I2C_CH7_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_RST_REG      ",             FPGA0_I2C_CH7_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH7_SEM_REG      ",             FPGA0_I2C_CH7_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_PRSCL_LO_REG ",             FPGA0_I2C_CH8_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_PRSCL_HI_REG ",             FPGA0_I2C_CH8_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_CTRL_REG     ",             FPGA0_I2C_CH8_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_TX_REG       ",             FPGA0_I2C_CH8_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_RX_REG       ",             FPGA0_I2C_CH8_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_CMD_REG      ",             FPGA0_I2C_CH8_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_STAT_REG     ",             FPGA0_I2C_CH8_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_MUX_SEL_REG  ",             FPGA0_I2C_CH8_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_RST_REG      ",             FPGA0_I2C_CH8_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH8_SEM_REG      ",             FPGA0_I2C_CH8_SEM_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_PRSCL_LO_REG ",             FPGA0_I2C_CH9_PRSCL_LO_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_PRSCL_HI_REG ",             FPGA0_I2C_CH9_PRSCL_HI_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_CTRL_REG     ",             FPGA0_I2C_CH9_CTRL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_TX_REG       ",             FPGA0_I2C_CH9_TX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_RX_REG       ",             FPGA0_I2C_CH9_RX_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_CMD_REG      ",             FPGA0_I2C_CH9_CMD_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_STAT_REG     ",             FPGA0_I2C_CH9_STAT_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_MUX_SEL_REG  ",             FPGA0_I2C_CH9_MUX_SEL_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_RST_REG      ",             FPGA0_I2C_CH9_RST_REG},
    LIPARI_FPGA_REGISTERS{"FPGA0_I2C_CH9_SEM_REG      ",             FPGA0_I2C_CH9_SEM_REG},
}


