package dps2100

// Register/Command offset
const (
    PAGE                      = 0x00
    OPERATION                 = 0x01
    ON_OFF_CONFIG             = 0x02
    CLEAR_FAULTS              = 0x03
    PAGE_PLUS_WRITE           = 0x05
    PAGE_PLUS_READ            = 0x06
    CAPABILITY                = 0x19
    QUERY                     = 0x1A
    SMBALERT_MASK             = 0x1B
    VOUT_MODE                 = 0x20
    COEFFICIENT               = 0x30
    FAN_CONFIG_1_2            = 0x3A
    FAN_COMMAND_1             = 0x3B
    IOUT_OC_FAULT_LIMIT       = 0x46
    IOUT_OC_WARN_LIMIT        = 0x4A
    OT_WARN_LIMIT             = 0x51
    IIN_OC_WARN_LIMIT         = 0x5D
    POUT_OP_WARN_LIMIT        = 0x6A
    PIN_OP_WARN_LIMIT         = 0x6B
    STATUS_WORD               = 0x79
    STATUS_VOUT               = 0x7A
    STATUS_IOUT               = 0x7B
    STATUS_INPUT              = 0x7C
    STATUS_TEMPERATURE        = 0x7D
    STATUS_CML                = 0x7E
    READ_STATUS_MFG_SPEC      = 0x80
    STATUS_FANS_1_2           = 0x81
      STATUS_FAN_FAULT          = (1<<7)
      STATUS_FAN_WARN           = (1<<5)
    READ_EIN                  = 0x86
    READ_EOUT                 = 0x87
    READ_VIN                  = 0x88
    READ_IIN                  = 0x89
    READ_VOUT                 = 0x8B
    READ_IOUT                 = 0x8C
    READ_TEMPERATURE_1        = 0x8D
    READ_TEMPERATURE_2        = 0x8E
    READ_TEMPERATURE_3        = 0x8F
    READ_FAN_SPEED_1          = 0x90
    READ_POUT                 = 0x96
    READ_PIN                  = 0x97
    PMBUS_REVISION            = 0x98
    MFR_ID                    = 0x99
      MFG_ID_BLK_SIZE         = 0x05  
    MFR_MODEL                 = 0x9A
      MFG_MODEL_BLK_SIZE      = 0x0C
    MFR_REVISION              = 0x9B
      MFG_REVISION_BLK_SIZE   = 0x04
    MFR_LOCATION              = 0x9C
      MFR_LOCATION_BLK_SIZE   = 0x02
    MFR_DATE                  = 0x9D
      MFG_DATE_BLK_SIZE       = 0x06
    MFR_SERIAL                = 0x9E
      MFR_SERIAL_BLK_SIZE     = 0x0E
    APP_PROFILE_SUPPORT       = 0x9F
    MFR_VIN_MIN               = 0xA0
    MFR_VIN_MAX               = 0xA1
    MFR_IIN_MAX               = 0xA2
    MFR_PIN_MAX               = 0xA3
    MFR_VOUT_MIN              = 0xA4
    MFR_VOUT_MAX              = 0xA5
    MFR_IOUT_MAX              = 0xA6
    MFR_POUT_MAX              = 0xA7
    MFR_TAMBIENT_MAX          = 0xA8
    MFR_TAMBIENT_MIN          = 0xA9
    MFR_EFFICIENCY_LL         = 0xAA
    MFR_EFFICIENCY_HL         = 0xAB
    MFR_MAX_TEMP_1            = 0xC0
    MFR_MAX_TEMP_2            = 0xC1
    MFR_MAX_TEMP_3            = 0xC2
    SMART_ON_CONFIG           = 0xD0
    MFR_HW_COMPATIBILITY      = 0xD4
    MFR_FWUPLOAD_CAPABILITY   = 0xD5
    MFR_FWUPLOAD_MODE         = 0xD6
        EXIT_FIRMWARE_UPLOAD_MODE = 0x00
        FIRMWARE_UPLOAD_MODE      = 0x01
    MFR_FWUPLOAD              = 0xD7
    MFR_FWUPLOAD_STATUS       = 0xD8
        FULL_IMAGE_RECEIVED         = 0x00
        FULL_IMAGE_NOT_RECEIVED_YET = 0x01
        BAD_IMAGE_RECEIVED          = 0x02
        IMAGE_NOT_SUPPORTED         = 0x04

    MFR_FW_REVISION           = 0xD9
        MFR_FW_REVISION_BLK_SIZE = 0x03
    MFR_BLACKBOX              = 0xDC
    MFR_REAL_TIME_BLACK_BOX   = 0xDD
    MFR_SYSTEM_BLACK_BOX      = 0xDE
    MFR_BLACKBOX_CONFIG       = 0xDF
    MFR_CLEAR_BLACKBOX        = 0xE0


)


